### ISSUE TITLE
Need custom function for nb01_nbi01_eco.csv translation table

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#135]
@edwardsmarc - we need four custom functions or rather one custom function that can population four attributes: WETLAND_TYPE, WET_VEG_COVER, WET_LANDFORM_MOD, and WET_LOCAL_MOD. You can see the code in the corresponding markdown file. It's fairly simple just lots of classes.

**Comment by edwardsmarc** [comment]
Some of these functions will return '-'.

Should that be a NULL, or does the CASFRI specs specify we should return '-'?

**Comment by prvernier** [comment]
Yes, I think that should be a NULL if the function returns a dash.

**Comment by edwardsmarc** [comment]
Validation function will test cases, extract the text value using substring, return true if text value, return false if dash, or no matching cases.

Translation function will do the same but just return the text. dashes won't be returned because they will be caught by the validation function. But we could add a catch to return NULL in the case of a dash in case we miss it during validation.

**Comment by edwardsmarc** [comment]
Can you check the logic for BO-B and FO-B.
They currently have the same logical test.

**Comment by prvernier** [comment]
Thanks, I found the error (in the BO-B logic) and fixed/pushed it.
