### ISSUE TITLE
Make photo year file valid

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#137]
Related to #136 

Make a version of the AB photo year file where 'not known' rows are removed.

All rows should have integer value for photo year.

**Comment by pedrogit** [comment]
On the other side I don't like the idea of throw away some polygons that might be usefull later.

We came to the conclusion that we should fix the original file because if we fix it in PostGIS then the table name in the translation table become invalid.

Why not fixing it in PostGIS and rename the table so we don't have to change the translation files? 

That would provide an example on how to fix an invalid file and we would not throw away information (the polygons) that might be usefull later.

**Comment by edwardsmarc** [comment]
That makes sense. Should we also fix the geometries in SQL then? Or just keep using the fixed version we made in #130

**Comment by pedrogit** [comment]
Should we add an UNKNOWN_VALUE error code?

**Comment by edwardsmarc** [comment]
Yes UNKNOWN_VALUE would make sense here.
