### ISSUE TITLE
Standardize CASFRI attribute names

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#139]
Change the following attribute names in tables and document changes in the specs:

CASFRI_AREA
CASFRI_PERIMETER
SRC_INV_AREA
PHOTOYEAR - make consistent

**Comment by prvernier** [comment]
You can see all attribute names here: https://prvernier.github.io/cas/

So far we have the follwoing suggested name changes (note that in a couple cases there are 2 options):

HDR tables:

SOURCE_DATA_PHOTOYEAR  -->  PHOTO_YEAR_SOURCE (or PHOTO_YEAR_SRC)
PHOTOYEAR_START  -->  PHOTO_YEAR_START
PHOTOYEAR_END  -->  PHOTO_YEAR_END

CAS tables:

GIS_AREA  -->  CASFRI_AREA
GIS_PERIMETER  -->  CASFRI_PERIMETER
INVENTORY AREA  -->  SRC_INV_AREA (or SRC_INVENTORY_AREA)
SOURCE_DATA_FORMAT  -->  SRC_DATA_FORMAT

**Comment by pedrogit** [comment]
Great! All good to me.

Why CROWN in CROWN_CLOSURE_UPPER and CROWN_CLOSURE_LOWER? Does CASFRI really has to refer to the crown?

**Comment by prvernier** [comment]
Okay, last chance to review before @edwardsmarc goes away. Hopefully, no more name changes after today since this affects a bunch of code and documents down the pipeline.

PHOTO_YEAR  -->  STAND_PHOTO_YEAR
SOURCE_DATA_PHOTOYEAR --> PHOTO_YEAR_SRC
PHOTOYEAR_START --> PHOTO_YEAR_START
PHOTOYEAR_END --> PHOTO_YEAR_END
GIS_AREA --> CASFRI_AREA
GIS_PERIMETER --> CASFRI_PERIMETER
INVENTORY AREA --> SRC_INV_AREA
SOURCE_DATA_FORMAT --> SRC_DATA_FORMAT
DIST_YR_1  -->  DIST_YEAR_1
DIST_1  -->  DIST_TYPE_1

**Comment by pedrogit** [comment]
Fine with me for this alpha release. We can still change things before the first major release.

**Comment by edwardsmarc** [comment]
Yes these all look great. Thanks @prvernier

**Comment by prvernier** [comment]
Made changes to all translation tables, casfri specs document, and inventory list.
