### ISSUE TITLE
Produce GEO table

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#141]
In addition to CAS, ECO, DST, HDR, LYR and NFL we need to produce a GEO table composed of the TT_MakeValid() geometry and the CAS_ID. Not sure if it should be a blocker for the next release.

**Comment by edwardsmarc** [comment]
I agree with this being a blocker. I'll make the tables this week.

**Comment by edwardsmarc** [comment]
What should the error code be for invalid geometries? Currently we specify INVALID_GEOMETRY but this doesn't work because the error code needs to be castable to type geometry.

i.e. this creates an error -  'INVALID_GEOMETRY'::geometry

We could return an empty geometry by using POLYGON EMPTY
  - e.g. geoIsValid(wkb_geometry|POLYGON EMPTY
  - i.e. this works and creates an empty polygon - 'POLYGON EMPTY'::geometry

Or we could use the geometry value directly instead of the geometry as text, the equivalent geometry for an empty polygon is 010300000000000000
  - e.g. geoIsValid(wkb_geometry|010300000000000000)

Another option is to actually return a polygon that we agree represents an error
  - e.g. geoIsValid(wkb_geometry|POLYGON((0 0, 0 0, 0 0, 0 0)))

**Comment by edwardsmarc** [comment]
My vote would be for POLYGON EMPTY because it is both a text representation that makes sense to someone reading the specs, but also a valid geometry when cast using ::geometry.

**Comment by edwardsmarc** [comment]
The issue with using POLYGON EMPTY is that in the CASFRI output this would be displayed as the geometry value 010300000000000000 which makes it harder to identify errors. Ideally the error code cast to the target type should be the same as the error code used in the translation table.

In which case we should use 010300000000000000.

**Comment by pedrogit** [comment]
Related to engine #144

**Comment by edwardsmarc** [comment]
Using POLYGON EMPTY as the error code for now. This may change based on #111
