### ISSUE TITLE
Translation rule NFL: layer and layer rank

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#203]
Translation_rules for layer and layer_rank in NFL is "copyInt('1')". My understanding is that you blindly assigned 1 to both. My opinion is it shouldn't. If layer 1 already been assigned to a polygon under LYR, NFL should be layer 2. The idea is the user should be able to query CASFRI flat table with layer = 1 and get the complete coverage of CASFRI with no overlap. This query is frequent. Most of the time, users are not interested to deal with the verticallity. They just wants to know the main vocation of the polygon given by layer = 1, no matter if it's a NFL or a LYR.  Layer is thus assigned at the polygon level and not at the component level.

**Comment by edwardsmarc** [comment]
What if there is no LYR data, and only one NFL layer? Would it be layer 1? And what if there is no LYR data but two NFL layers, then would they be layer 1 and layer 2?

Currently for AB and NWT I think hard coding the layer as 1 and 2 in the translation tables is producing the desired result. Those inventories have a set of attributes for each layer, and they can either be filled with LYR data or NFL data. So CASFRI for these will never have multiple LYR and/or NFL entries in the same layer.

BC and NB are a different story and we should review the logic to figure out the correct translation rules. It could be tricky as we will need to reference other tables to determine the correct layer value. We could consider making LAYER a derived attribute calculated after translation. Or we will need to write some complex helper functions to lookup what layers have already been assigned.

**Comment by MelinaHoule** [comment]
If no LYR but NFL, layer in NFL should be 1. If no LYR but 2 NFL, layer should be 1 and 2 according to priority. 

I can't talk about the best strategy  right now. I'm not familiar enough with the engine. But from my experience, users often ask to get the complete coverage of CASFRI with no verticallity. Which means, for each polygon, they want the main canopy cover when present or landcover class when it is not forested. Right now, by forcing layer = 1 in NFL in BC and NB, we will introduce duplicates where LYR record is present.  

Lets asked John Cosco some precisions about the definition of layer and layer_rank.

**Comment by edwardsmarc** [comment]
Logic for assigning LAYER translation rules in source inventories where number of layers is fixed (e.g. AB and NT always have 2 slots which can be either forest or NFL info):
* Slot 1 is always assigned layer 1, slot 2 is always assigned layer 2.
* This works using the existing system of hard coding layer values in the attribute dependencies table.
* There should be 4 translations, layer 1 and 2 forest, layer 1 and 2 nfl.
* Hard coding works because the layer 1 and 2 attributes can only hold forest OR NFL info, not both.

Logic for assigning LAYER translation rules in source inventories where number of layers is variable (e.g. BC could have multiple forest layers and/or multiple NFL layers; NB can have one or two forest layers, and one NFL layer):
* First we need to know every possible translation rule for LYR and NFL layers. For NB this would be 3 rules, one for forest layer 1 info, one for forest layer 2 info, and one for NFL.
* Layer translation rule would then be written as a custom function that tests the following:
  * What table is being translated (e.g. NFL layer 1)
  * Does data exists for forest layer 1?
  * Does data exist for forest layer 2?
  * Does data exist for nfl?
  * Assign layer number based on presence of other layers.
* For example in NB, when translating the NFL layer, if forest layer 1 and forest layer 2 data exist, NFL would be assigned layer value 3. If only forest layer 1 data exist, NFL would be assigned layer value 2.
* This will require writing a potentially complex custom sql function for each standard.

**Comment by pedrogit** [comment]
We already discussed about this an we said that we could design a helper function returning the "rank" of the first group of attribute having a non null value. e.g.

TT_RankOfFirstNonNull({lyr_1_att1, lyr_1_att_2,...}, {lyr_2_att1, lyr_2_att_2,...}, {nfl_att1, nfl_att2,...})

So that:

- if lyr_1_att1, lyr_1_att2 and lyr_2_att1 are all NULL but lyr_2_att_2 is not NULL then it would return 2.

- if lyr_1_att1, lyr_1_att2, lyr_2_att1, lyr_2_att2 are all NULL but nfl_att1 or nfl_att2 are not NULL then it would return 3.

- etc...

**Comment by edwardsmarc** [comment]
Are you referring to #218?

NUM_OF_LAYERS
TT_NumberOfNotNull() - this is for counting layers. It returns the number of not null arguments.

That function works for counting all layers, but not for assigning LAYER values.

I don't understand how your TT_RankOfFirstNonNull() would work for NFL layer 1 for example. If lyr_1_att1 and lyr_2_att1 are not null, then the NFL row should be LAYER = 3, because it's the third layer we have data for. In you function it would get a value of 1 (Maybe I am misunderstanding your function?).

I think we need a function that takes the layer number from the dependency table as an input. That way we can calculate the rank of the nth argument in the function based on the not nulls that have come before it. 

If we consider BC10 and assume that both layers could have 1 NFL component, we have a maximum possible NUM_OF_LAYERS of 4. The dependency table would look like this, with rows 1 - 4 corresponding to translations for tables LYR 1, LYR 2, NFL 1, NFL 2.

| inventory_id | layer | layer_rank |
| ------------- | ------------- | ------------- |
| BC10 | 1 | 1 |
| BC10 | 2 | 2 |
| BC10 | 3 | 3 |
| BC10 | 4 | 4 |

We would write a function that takes the layer number as input. So assuming all four layers have data, the function for NFL layer 1 (third row in the table) would be something like:

TT_NotNullRank(3, {lyr_1_att1, lyr_1_att_2,...}, {lyr_2_att1, lyr_2_att_2,...}, {nfl_1_att1, nfl_1_att2,...}, {nfl_2_att1, nfl_2_att2,...})

and would return a value of 3. If all the LYR attributes were null it would return 1.

Question is, with TT_CreateMappingView(), can layer values from the dependency table be used as arguments in translation functions?

**Comment by edwardsmarc** [comment]
I think moving forward, we need to acknowledge that we currently have 2 types of inventories with respect to layer assignments. Grouping future inventories like this might help us in designing translations:

# Fixed
The LAYER value is directly associated with the attributes in the source data. Only one value (LYR or NFL) can be returned per layer. Whatever value (LYR or NFL) is returned from the layer 1 attributes will get a LAYER value of 1. Whatever value (LYR or NFL) is returned from the layer 2 attributes will get a LAYER value of 2.  Current examples are AB and NT. Examples of layer 1 attributes in AB are sp1 and anth_veg. Examples of layer 2 attributes in AB are usp1 and uanth_veg. 

Another way of thinking about this is that the NFL data has already been assigned a layer value in the source data. All we have to do is copy over the layer value using coptText(layer) in the translation table.

# Variable
The LAYER value is not directly associated with the attributes in the source data. The assignment of LAYER value depends on what other layers are assigned above it. e.g. NFL could be layer 1 if no LYR layers exist, or layer 3 if two LYR layers exist. Current examples are BC and NB. 

Another way of thinking about this is that layer values have not been assigned for NFL data. They likely have been for LYR data, but we need to figure out where the NFL layer(s) fit in. In these cases we would need something like the TT_NotNullRank() function proposed above.

**Comment by pedrogit** [comment]
TT_RankOfFirstNonNull() should actually be named TT_RankOfFirstNull(). Make sence now?

**Comment by edwardsmarc** [comment]
But isn't it returning the rank of the first no null argument?

Either way, I see how your function or something similar could be used to get the layer for a single translation (e.g. LYR 1). But I don't see how it could be used as a single generic function that works for all translations (e.g. LYR 1, LYR 2, NFL 1, NFL 2).  How can it return the correct layer value using the same input arguments each time? How does the function know which translation is being run?

**Comment by pedrogit** [comment]
Let's agree on some rules. For an inventory having a maximum of two forested layers:

1) for LYR layer 1, LAYER should always be equal to 1 right?

2) for LYR layer 2, LAYER should always be equal to 2 right? Could it be 1?

3) for NFL layer 1 and any other NFL component, LAYER can be either 1, 2 or 3 depending on the values of the sp1, sp2, sp3, us_sp1, us_sp2 and us_sp3 attributes. If they are all NULL, then LAYER is 1. If only the ones for layer 1 (sp1, sp2, sp3) are not NULL then LAYER is 2 and if all attributes are non NULL then LAYER is 3, right?

**Comment by edwardsmarc** [comment]
Yes agreed on all those rules.

LYR layer 2 should always be equal to 2.

**Comment by pedrogit** [comment]
Then it becomes simple:

- the LYR translation table takes its LAYER value from the layer attribute hardcoded in the VIEW produced by TT_CreateMappingView()

- the NFL translation table uses TT_NumberOfNotNull({sp1, sp2, sp3}, {us_sp1, us_sp2, us_sp3}, {nat_nonveg, anth_noveg, anthro_veg, nonfor_veg}) to determine its layer value.

This implies that the layer value for NFL is always equal to NUM_OF_LAYER since both are determined by TT_NumberOfNotNull({sp1, sp2, sp3}, {us_sp1, us_sp2, us_sp3}, {nat_nonveg, anth_noveg, anthro_veg, nonfor_veg}).

Now the VIEW does not give access to species values from both the canopy and the understory at the same time but we can fix this by adding a 'NFL_LAYER' column to attribute_dependencies and add those attributes to all rows used when translating NFL.

**Comment by edwardsmarc** [comment]
This works well for NB where we have max 2 LYR layers and 1 NFL layer.

What about cases with multiple NFL layers? BC could be an example. Do we expect to find others?

Do we ever expect to find more than 2 LYR layers? Even if we do, I expect the LAYER values in LYR tables can always be hard coded since they should always be defined as a specific layer in the source data.

**Comment by pedrogit** [comment]
Let's say you could have 2 NFL layers...

We agree that one of them could become LAYER = 1, 2, 3 or 4 and the other one could become LAYER = 1, 2, 3 but not 4 because there is a hierarchy like for forested canopy and understory.

You would also need to create a different translation table for each of them because the source attributes and the rules will be different.

Then you would simply generalize the use of the TT_NumberOfNotNull(). The upper NFL layer would use only three sets of attribute to determine LAYER:

TT_NumberOfNotNull({sp1, sp2, sp3}, {us_sp1, us_sp2, us_sp3}, {nfl1, nfl2, nfl3})

and the lower layer would use all four of them:

TT_NumberOfNotNull({sp1, sp2, sp3}, {us_sp1, us_sp2, us_sp3}, {nfl1, nfl2, nfl3}, {nfl4, nfl5, nfl6})

Would that work?

**Comment by MelinaHoule** [comment]
It makes sense.

To test it, Manitoba (Duck_mountain and Porcupine_mountain) have polygons with multiples NFL. Prince Albert National Park have polygons with multiples LYR combined with multiples NFL.

**Comment by edwardsmarc** [comment]
Yes, great point about needing different translation tables. 

For BC your example is correct because we would be searching for NFL layers in completely different columns containing unique values.

This might not always be the case, for example a source inventory could have an nfl_1 and nfl_2 column, both containing the same possible set of values. This would allow the same translation rule to be applied using a VIEW. However we have not encountered that yet and I have no idea if it occurs in any inventory. If we do encounter this, we can always accommodate it by using a second translation table.

**Comment by pedrogit** [comment]
So are we happy with the answers:

We need:

- to implement TT_NumberOfNotNull()
- a new NFL-LAYER column in the attribute_dependencies table
- to modify the translation tables accordingly

**Comment by MelinaHoule** [comment]
In Prince Alberts National Park, that case happen. Because of their classification. They can have up to 3 level of NFL and they split the code using lowland and upland, e.g., lowland herb, upland herb,..... which are resume in CASFRI standard as herb. The stand_structure is horizontal. That may explain why both lowland (wet site) and upland(dry site) happen in the same polygon.

**Comment by edwardsmarc** [comment]
Yes happy with those conclusions.

I think we will need to TT_NumberOfNotNull() for the NB nfl table. Currently it has no nfl translations written.

**Comment by pedrogit** [comment]
Another maybe simpler way to achieve the same goal without having to add a line for NFL in the attribute_dependency table:

- Make TT_CreateMappingView() to add a constant specifying the max_layer_number possible for this layer. For LYR layer 1 this number is 1, for LYR layer 2 this number is 2 for NFL layer 1 this number is 3 and for NFL layer 2 this number is 4.

- Add a max_number parameter to TT_NumberOfNotNull() so that is will stop counting the number of NULL when reaching the max_number.

- Make each translation rule look like: TT_NumberOfNotNull(..., max_layer_number);

I think that's a more generic better solution.

**Comment by edwardsmarc** [comment]
Nice idea. What would the translation rule look like for each table?....

LYR layer 1 - NumberOfNotNull({att1, att2}, {att3, att4}, {att5, att6}, {att7, att8}, 1)
LYR layer 2 - NumberOfNotNull({att1, att2}, {att3, att4}, {att5, att6}, {att7, att8}, 2)
NFL layer 1 - NumberOfNotNull({att1, att2}, {att3, att4}, {att5, att6}, {att7, att8}, 3)
NFL layer 2 - NumberOfNotNull({att1, att2}, {att3, att4}, {att5, att6}, {att7, att8}, 4)

I guess it would also be crucial to have validation rules corresponding to the layer being processed:

LYR layer 1 - NotNull(att1); NotNull(att2)
LYR layer 2 - NotNull(att3); NotNull(att4)
NFL layer 1 - NotNull(att5); NotNull(att6)
NFL layer 2 - NotNull(att7); NotNull(att8)

And we would have a dependency table that looked like this (@pedrogit would we feed the max_layer_number value into the translation rules from the dependency table? I suppose we wouldn't need the layer attribute any more?):

inventory_id | layer | max_layer_number
--------------|-------|---------------------
XXxx             |       ? |                             1
XXxx             |       ? |                             2
XXxx             |       ? |                             3
XXxx             |       ? |                             4

**Comment by pedrogit** [comment]
> Nice idea. What would the translation rule look like for each table?....
> 
> LYR layer 1 - NumberOfNotNull({att1, att2}, {att3, att4}, {att5, att6}, {att7, att8}, 1)
> LYR layer 2 - NumberOfNotNull({att1, att2}, {att3, att4}, {att5, att6}, {att7, att8}, 2)
> NFL layer 1 - NumberOfNotNull({att1, att2}, {att3, att4}, {att5, att6}, {att7, att8}, 3)
> NFL layer 2 - NumberOfNotNull({att1, att2}, {att3, att4}, {att5, att6}, {att7, att8}, 4)

The rule would be generic and the same for each table:

numberOfNotNull({att1, att2}, {att3, att4}, {att5, att6}, {att7, att8}, max_layer_number)

> I guess it would also be crucial to have validation rules corresponding to the layer being processed:
> 
> LYR layer 1 - NotNull(att1); NotNull(att2)
> LYR layer 2 - NotNull(att3); NotNull(att4)
> NFL layer 1 - NotNull(att5); NotNull(att6)
> NFL layer 2 - NotNull(att7); NotNull(att8)

No need because NumberOfNotNull() is expecting some NULL values...

> And we would have a dependency table that looked like this (@pedrogit would we feed the max_layer_number value into the translation rules from the dependency table? I suppose we wouldn't need the layer attribute any more?):

max_layer_number would be set by TT_CreateMappingView() as an extra field. It will use the keyword and the layer arguments to determine the right max_layer_number to set.

No more need for an extra NFL lines in attribute_dependency.csv (that's the point)...

**Comment by edwardsmarc** [comment]
> No need because NumberOfNotNull() is expecting some NULL values...

What if you had null values for the layer you are translating? But values for other layers? Then it would return a layer value for a layer that doesn't exist. Maybe the filtering in CreateMappingView() removes such rows? For example, the following translation rule in the LYR1 table would return a value of 1, even though there is no LYR info. I'd have thought an error code would be needed here:
`numberOfNotNull({NULL, NULL}, {NULL, NULL}, {val, val}, {val, val}, 1)`

> It will use the keyword and the layer arguments to determine the right max_layer_number to set.

Where does it get the layer arguments from? Whats the keyword?

**Comment by pedrogit** [comment]
CreateMappingView() MUST removes such rows...

For all LYR, NFL, DST rows, CreateMappingView() is always called with the corresponding keyword and layer number. Values for max_layer_number are determined like this LYR1 = 1, LYR2 = 2, NFL1 = 3, NFL2 = 4. DST1 = 1, DST2 = 2.

If we ever get NFL3 (e.g. for BC), it will have it's own row in the attribute_dependencies table and we could assign a value for max_layer_number there. But it probably more simple to do:

max_layer_number = right(LYRkeyword, 1) + right(NFLkeyword, 1)

e.g.

max_layer_number = right('LYR1', 1) + right('NFL2', 1) = 3

max_layer_number = right('LYR2', 1) + right('NFL3', 1) = 5

**Comment by edwardsmarc** [comment]
Just pushed TT_NumberOfNotNull()

**Comment by edwardsmarc** [comment]
Next step is to update translation tables to use TT_NumberOfNotNull(). Arguments should be the same as NUM_OF_LAYERS (#218) - i.e. the required columns indicating a layer is present, for all possible layers in an FRI.

Then need to update workflow scripts to use correct TT_CreateMappingView(). This will subset the source table to only include rows corresponding to the layer being translated. Required attributes are the keyword, e.g. LYR1, and the max_layer_number as defined in the comment above.

For example, if LYR1 table is being translated, TT_CreateMappingView() would use keyword LYR1 and max_layer_number of 1. The VIEW would only report rows with values for LYR1 attributes, and all rows would return a layer value of 1.

Final change is to add column to dependency table named NFL_LAYER containing all attributes used in TT_NumberOfNotNull(). This will be used by both LYR and NFL VIEWs to access the full set of attributes that would otherwise be filtered out (e.g. LYR VIEW would not usually include NFL attributes but they are needed by TT_NumberOfNotNull()).

**Comment by edwardsmarc** [comment]
In some cases when making views, we will need to map two sets of values to one column name. For example when making a view for LYR2, the usp1 column needs to be mapped to sp1. But we also need both the original usp1 and sp1 columns in order to calculate num_of_layers and layers.

Solution is to set up some specific lyr attributes for all source attributes used in numberOfNotNull(). In the dependency table for the generic row (every FRI will need a generic row for this to work), replace the attribute names in NUM_NOT_NULL with lyr_att_1, lyr_att_2 etc. Use these names in the translation table also. Each layer row will use the actual source attribute names.

**Comment by edwardsmarc** [comment]
See #253 

Last step in this issue is to assign LAYER_RANK values to all FRIs

**Comment by edwardsmarc** [comment]
LAYER_RANK
BC08  = 1
BC10 = l1_for_cover_rank_cd and l2_for_cover_rank_cd
AB06/AB16/NT = no rank attribute
NB01 = no rank attribute
NB02 = has lpriority with values 1 and 2 in forest dataset. Not sure if this is a rank. No documentation?

**Comment by edwardsmarc** [comment]
All done except NB02. Waiting to get documentation.

**Comment by edwardsmarc** [comment]
Manual is inconclusive on lpriority. Leaving this out. Did not hear back from query to NB contact.
