### ISSUE TITLE
Constraints - Geometry error code found in stand_photo_year

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#237]
In Alberta, if the intersection between ab_photoyear and a rawfri polygon is invalid, stand_photo_year can't be extracted and the error code in the translated table is -7779.  -7779 means invalid geometry.  I understand the error comes from an invalid geometry, but I don't think that type of error should be reported in stand_photo_year. 

Since we will be working on temporalization soon, we should start thinking on adding **stand_photo_year_start** and **stand_photo_year_end** in CAS table to highlight the validity of each polygon within time. By having those 2 columns, when the intersection doesn't work or when photo year for a polygon is unknown, we will extract default photo year values from the inventory_list_casXX.csv respective to the  Identification_ID.

**Comment by edwardsmarc** [comment]
Maybe INVALID_VALUE is more appropriate?

@pedrogit - We would need to add this error in the translation table right? Since it's not the default error for the function.

**Comment by pedrogit** [comment]
Weren't invalid geoemtries fixed by some SQL code before the beginning of the translation? I guess we never got this problem because we always fixed the photo_year table using the devel code before trying to execute the produceCASFRI code. So adding those line to 02_cas.sql would fix the problem.

After fixing this, any unknown values remain?

However, if in any case some geometry related bug remains, I think I would go with UNKNOWN_VALUE. you can set this error code directly in the translation table to overwrite the default error code. default error codes are defined by the TT_DefaultErrorCode() in the engine helper functions and by TT_DefaultProjectErrorCode() in CASFRI.

**Comment by edwardsmarc** [comment]
@MelinaHoule - which validation function is returning the error? geoIsValid or geoIntersects?

geoIsValid will return errors if the geometry is invalid. As @pedrogit mentioned we shouldn't get this error once the photo year table has been validated in #236.

geoIntersects will return errors if there is no intersecting photo year polygon.

**Comment by MelinaHoule** [comment]
The error code is associated with geoIsValid.

**Comment by pedrogit** [comment]
I guess this issue is the same as #244.

**Comment by pedrogit** [comment]
Check all distinct values after a complete translation and adjust the constraints.

**Comment by edwardsmarc** [comment]
Closed in error, reopening

**Comment by pedrogit** [comment]
Checked by constraint 1.21. Definitely fixed.
