### ISSUE TITLE
Use notMatchList to translate default 0 as unused instead of out of range

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#247]
For many attributes, default 0 were handle by isGreaterThan(), isLessThan() and isBetween() by returning out_of_range (-9999). We created notMatchList() (see commit 8082dc8ccae1c3a8139e32a686c2c1dac9a18ecd) to distinguish default value from real out of range. 

notMatchList will allow us to flag default value as not used by CASFRI (-9994). 

Need to be implemented in all inventories having default numeric value in rawfri set as 0.

**Comment by edwardsmarc** [comment]
Look at this when we review the error codes during validation

**Comment by pedrogit** [comment]
Do we have any idea of which source attributes use 0 as NULL?

**Comment by edwardsmarc** [comment]
Not really, we would have to review each case. 0 is often used as NULL for species percent values.

**Comment by pedrogit** [comment]
What is the status here?

**Comment by edwardsmarc** [comment]
This should have been fixed with my recent changes to standardize error codes.

In general, I've been catching zero values and translating as NULL_VALUE/-8888.

I've been allowing zero values in crown closure since it's included in the specs, but I've been catching them in height and species percent for example.

**Comment by edwardsmarc** [comment]
I'll close this after making some final changes:

ON and YT01/02 should catch CC zeros as nulls
NT CC translation is incorrect. Should be groupings not simply multiply.
