### ISSUE TITLE
Develop and apply system for naming attributes in dependency table and generic translation table

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#263]
Currently generic translation tables use a mix of attribute names. Most attribute names are the same as the first translation table that was developed for that standard. In some cases 'dummy' variables (e.g. dummy1, dummy2 etc.) are used to allow attributes to be assigned NULL where needed.

An example of this is LAYER calculations in BC where layer 2 attributes are mapped to dummy attributes (used in translation tables) for BC10, but assigned NULL in BC08 where there is no layer 2 info. In this way, the layer 2 attributes are essentially ignored during the BC08 translation.

* We should use more meaningful names instead of "dummy". e.g. nfl_att_1 etc.
* We could extend this concept so that all attributes in the translation tables and generic rows of the attribute_dependency tables use generic names. For example all species names could be sp1, sp2 etc. All NFL attributes could be nfl1, nfl2 etc. This might make the tables and attribute dependency table easier to read/understand.

**Comment by pedrogit** [comment]
I like the idea to have generic names across all standards. i.e. same names for BC, AB, etc...

We need a naming rule that reflect the original attribute type (sp, nfl, dst) and the natural target attribute names.

e.g.
sp1, sp2, ...
sp1pct, sp2pct,...
nfl1, nfl2, nfl3
dst1, dst2, dst3

I don't know about the others...

**Comment by pedrogit** [comment]
Here is a more elaborated proposition:

- **"CASFRI attributes"** are the final translated CASFRI attributes. e.g. species_1, soil_moist_reg, stand_structure.

- **"Translation table attributes"** are the attributes used in the translation table rules. e.g. sp1, moist_reg, struc_val. They are the attributes on which depend "CASFRI attributes" translation. They must have the same names as "target attributes". One "CASFRI attribute" can depend on many "target attributes" to be translated. e.g. cas_id generally depends on a mixture of inventory_id, src_filename, poly_id and ogc_fid.

- **"Target attributes"** are attributes used in the generic rows of the attribute_dependencies.csv table on which source attributes are mapped by TT_CreateMappingView(). e.g. for AB: sp1, moist_reg, struc_val. Each column in the attribute_dependencies.csv establish the dependency between CASFRI attributes and translation table attributes.

- **"Source attributes"** are the attributes of the source table to be mapped to the "translation table attributes" (or "target attributes"). e.g. for AB06 layer 2:  usp1, umoist_reg, ustruc_val

Source attribute names are fixed since they refer to source tables attributes. We can not modify them.

Right now, as stated in a the first comment, 

In general the proposition is to name "target attributes" the same as CASFRI translation table attributesattributes. e.g.

**Comment by edwardsmarc** [comment]
I agree with this system.

The only tricky part, which you mention above, is when two source attributes need to be mapped to the same target attribute. This only currently occurs for the species and layer attributes. I think your fix of using '_other' is acceptable. Another option would be using '_layer' for the attributes used in LAYER, NUM_OF_LAYERS, and STAND_STRUCTURE.

This system should be applied along with #358.

I'll try testing it out for BC10 while fixing #362.
