### ISSUE TITLE
YT02 NFL - custom helper functions needed

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#294]
Custom helper functions are needed for the following NFL attributes:

- NAT_NON_VEG
- NON_FOR_ANTH
- NON_FOR_VEG
- SOIL_MOIST_REG
- CROWN_CLOSURE_UPPER, LOWER
- HEIGHT_UPPER, LOWER

Below is the equivalent R code:

```
# NFL ATTRIBUTES
yt02 = mutate(yt02,
    
    nat_non_veg = case_when(
        type_lnd %in% c('','VF','VN','NU') ~ "NULL_VALUE",
        type_lnd %in% c("NW","NS","NE") & !class %in% c('R','L','RS','E','S','B','RR') ~ "NOT_IN_SET",
        type_lnd %in% c("NW","NS","NE") & landpos=="A" ~ "AP",
        TRUE ~ mapvalues(class,c('R','L','RS','E','S','B','RR'),c('RI','LA','WS','EX','SA','EX','RK'))),

    non_for_anth=case_when(
        !type_lnd=='NU' ~ "NULL_VALUE",
        type_lnd=='NU' & !class %in% c('RD','G','T') ~ "NOT_IN_SET",
        TRUE ~ mapvalues(class, c('RD','G','T'), c('OT','OT','OT'))), # Can we do better than OT?

    non_for_veg=case_when(
        !type_lnd=='VN' ~ "NULL_VALUE",
        type_lnd=='VN' & !class %in% c('S','H','C','M') ~ "NOT_IN_SET",
        type_lnd=='VN' & cl_mod %in% c('TS','TSo','TSc') ~ "ST",
        type_lnd=='VN' & cl_mod=='LS' ~ "SL",
        type_lnd=='VN' & class=='C' ~ "BR",
        type_lnd=='VN' & class %in% c('H','M') ~ "HE",
        TRUE ~ "Something missing?"),

    nfl_soil_moist_reg = case_when(
        (nat_non_veg=="NULL_VALUE" & non_for_anth=="NULL_VALUE" & non_for_veg=="NULL_VALUE") ~ "NULL_VALUE",
        (!nat_non_veg=="NULL_VALUE" | !non_for_anth=="NULL_VALUE" | !non_for_veg=="NULL_VALUE") & smr=="" ~ "EMPTY_STRING", 
        (!nat_non_veg=="NULL_VALUE" | !non_for_anth=="NULL_VALUE" | !non_for_veg=="NULL_VALUE") & !smr %in% c('a','A','d','D','m','M','w','W') ~ "NOT_IN_SET", 
        TRUE ~ mapvalues(smr, c('a','A','d','D','m','M','w','W'), c('A','A','D','D','F','F','W','W'))),

    nfl_structure_per=0,

    nfl_layer="TO_BE_CALCULATED",

    nfl_layer_rank="TO_BE_CALCULATED",

    nfl_crown_closure_upper = case_when(
        (nat_non_veg=="NULL_VALUE" & non_for_anth=="NULL_VALUE" & non_for_veg=="NULL_VALUE") ~ as.numeric(-8888),
        (!nat_non_veg=="NULL_VALUE" | !non_for_anth=="NULL_VALUE" | !non_for_veg=="NULL_VALUE") & (cc<0 | cc>100) ~ as.numeric(-9999), 
        TRUE ~ as.numeric(cc)),

    nfl_crown_closure_lower = case_when(
        (nat_non_veg=="NULL_VALUE" & non_for_anth=="NULL_VALUE" & non_for_veg=="NULL_VALUE") ~ as.numeric(-8888),
        (!nat_non_veg=="NULL_VALUE" | !non_for_anth=="NULL_VALUE" | !non_for_veg=="NULL_VALUE") & (cc<0 | cc>100) ~ as.numeric(-9999), 
        TRUE ~ as.numeric(cc)),

    nfl_height_upper = case_when(
        (nat_non_veg=="NULL_VALUE" & non_for_anth=="NULL_VALUE" & non_for_veg=="NULL_VALUE") ~ as.numeric(-8888),
        (!nat_non_veg=="NULL_VALUE" | !non_for_anth=="NULL_VALUE" | !non_for_veg=="NULL_VALUE") & (avg_ht<0 | avg_ht>100) ~ as.numeric(-9999), 
        TRUE ~ as.numeric(avg_ht)),

    nfl_height_lower = case_when(
        (nat_non_veg=="NULL_VALUE" & non_for_anth=="NULL_VALUE" & non_for_veg=="NULL_VALUE") ~ as.numeric(-8888),
        (!nat_non_veg=="NULL_VALUE" | !non_for_anth=="NULL_VALUE" | !non_for_veg=="NULL_VALUE") & (avg_ht<0 | avg_ht>100) ~ as.numeric(-9999), 
        TRUE ~ as.numeric(avg_ht)),

)
```

**Comment by edwardsmarc** [comment]
Questioning whether soil moisture, height, and crown closure should be reported in NFL given that they use the same attributes as the forested info. NFL table should only report these if they are specific to the NFL layer.

Soil moisture - 
**"Soil moisture regime is interpreted for all vegetated polygons, burned areas and exposed soil using the classes in Table 5."** - this suggests soil moisture does apply to the nfl layer as long as it meets the criteria mentioned.

Crown closure -
**"Crown closure is the percentage of ground area covered by the vertically projected tree crowns....Crown closure is estimated for all tree layers independent of each other."**

Height -
**"Tree height is estimated for leading tree species in the canopy based upon an average of dominant and codominant tree heights....In multiple layered stands, the stand height attributes will be described for each layer"**

 Conclusion - add soil moisture to NFL but not height or CC. Note that soil moisture may be removed later depending on #230

Only add soil moisture if NFL has a non_for_veg attribute, or a nat_non_veg casfri attribute of EX (because I think this covers exposed land and burned areas based on the rules above).

**Comment by edwardsmarc** [comment]
## Converting to validation and translation functions in SQL

### nat_non_veg
#### validation
notEmpty(type_lnd)
matchList({"NW","NS","NE"}|NULL_VALUE)
yvi01_nat_non_veg_validation(xxxxxx|NOT_IN_SET)
  * type_lnd %in% c("NW","NS","NE") & !class %in% c('R','L','RS','E','S','B','RR')
  * OR type_lnd %in% c("NW","NS","NE") & landpos=="A"

#### translation
yvi01_nat_non_veg_translation(xxxxxx)
  * type_lnd %in% c("NW","NS","NE") & mapText(class,{'R','L','RS','E','S','B','RR'},{'RI','LA','WS','EX','SA','EX','RK'})
  * type_lnd %in% c("NW","NS","NE") & landpos=="A"
 
### non_for_anth
#### validation
matchList({'NU'}|NULL_VALUE)
matchList({'RD','G','T'}|NOT_IN_SET)

#### translation
mapText(class, {'RD','G','T'}, {'OT','OT','OT'})

### non_for_veg
#### validation
matchList(type_lnd, {'VN'}|NULL_VALUE)
matchList(class, {'S','H','C','M'})
yvi01_non_for_veg_validation(xxxxxx|NOT_IN_SET)

#### translation
yvi01_non_for_veg_translation(xxxxxx)
  * mapText(cl_mod, {'TS','TSo','TSc','LS'}, {'ST','ST','ST','SL'})
  * mapText(class, {'C','H','M'}, {'BR','HE','HE'})

### nfl soil_moist_reg
#### validation
yvi01_nfl_soil_moisture_validation(xxxxxx|NOT_APPLICABLE)
* if non_for_veg IN (x,y,z) OR nat_non_veg IN (EX), return true
#### translation
mapText(smr, {'a','A','d','D','m','M','w','W'}, {'A','A','D','D','F','F','W','W'})
