### ISSUE TITLE
List of CASFRI validations to check

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#300]
Starting a list of validations to check once CASFRI has been built.

EDITED
1. 
STAND_STRUCTURE of M should always have NUM_OF_LAYERS > 1
STAND_STRUCTURE of S should always have 1 LYR row
STAND_STRUCTURE of M should always have > 1 LYR row
NUM_OF_LAYERS should be >0

These are two very different tests. One test is between STAND_STRUCTURE  and NUM_OF_LAYERS which are in the same table and can be implemented with a constraint.

The other is between two tables and must be implemented with a test on a join.

**Comment by pedrogit** [comment]
- Check that NUM_OF_LAYERS actually matches the highest LAYER number for a same CAS_ID.

- Check that no two CAS_ID have the same LAYER number (this is checked when trying to apply the (cas_id, layer) primary key).

- Check that the LAYER number actually start at 1 for each CAS_ID

**Comment by pedrogit** [comment]
We could implement those check in the form of a test script similar to the other ones to be run after the creation of CASFRI50 in the workflow.

**Comment by pedrogit** [comment]
Now which checks should be implemented as database constraints and which one should be implemented as simple tests at the end of CASFRI translation?

**Comment by kdarndt** [comment]
Hi Pierre,

I tend to agree with you.  A few more thoughts below.

(1) the check sounds incorrect to me.  STAND_STRUCTURE could be "S" with NUM_OF_LAYERS >1 since NUM_OF_LAYERS includes NFL layers.  I think you'll need to check STAND_STRUCTURE with number of layers in the LYR table only.

Because you would have to check the LYR table instead of simply NUM_OF_LAYERS, this sounds like something not easily done in the database since it is a check across tables and rows (unless using a trigger function, but you're probably just as well to put it with your other external validation procedures).

(3) will be checked by the primary key (within the table).

(6) With lookup tables and foreign keys

(7) Should you check if greater than 1900 (if that's the first valid year in temporalization)?

(9) Definitely, through not null constraint.

(10) Possibly through a constraint check using PostGIS is_valid()?

(11) Similar to (6) or through check constraints if not possible.

**Comment by edwardsmarc** [comment]
I've update 1. based on our recent stand_structure updates.

**Comment by pedrogit** [comment]
If we already check that the relationship between STAND_STRUCTURE is fine, can we then only check that the number of joined layer in LYR and NFL = NUM_OF_LAYERS? I guess yes...

**Comment by edwardsmarc** [comment]
Yes I think so to. 

The only other consideration is whether NUM_OF_LAYERS = 0 is acceptable? This would occur in polygons with only DST info. We had discussed adding empty LYR rows for these cases.

**Comment by pedrogit** [comment]
Closed with https://github.com/edwardsmarc/CASFRI/commit/de2086e6a27776c05af8b4c197a8082c8ad1d318

**Comment by kdarndt** [comment]
> Yes I think so to.
> 
> The only other consideration is whether NUM_OF_LAYERS = 0 is acceptable? This would occur in polygons with only DST info. We had discussed adding empty LYR rows for these cases.

I am just curious what was implemented with this? I believe we had also suggested an "unknown" value for NUM_OF_LAYERS which would be my preference rather than mocking up records.

**Comment by pedrogit** [comment]
This issue is simply about implementing the test, which for now does not pass. The test, located in 01_addConstraints.sql in this case, accept values > 0 and -8886 (UNKNOWN_VALUE).

Now the issue is #340 and it hasn't been adressed yet. #339 and #272 are also related.
