### ISSUE TITLE
Can't create PRIMARY KEY when producing casfri50.dst_all 

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#305]
ERROR:  could not create unique index "dst_all_pkey"
DETAIL:  Key (cas_id, layer)=(NB01-xxxxxxxxxFOREST-xxxxxxxxxx-0000661600-0820445, 1) is duplicated.

**Comment by pedrogit** [comment]
This is because LAYER is hardcoded to be 1 in the translation table, even when it is reused for layer 2. It should be translated using the VIEW layer attribute instead.

**Comment by pedrogit** [comment]
Now the primary key constraint fails because all LAYER=-8886. If LAYER is UNKNOWN, there should be only one instance of it per CAS_ID and the couple CAS_ID, LAYER, shich form the primary key, should be unique.

**Comment by pedrogit** [comment]
Same issue with lyr_all. SK rows have duplicate CAS_ID, LAYER couples preventing the application of the primary key constraint:

SELECT cas_id, layer
FROM casfri50.lyr_all
GROUP BY cas_id, layer
HAVING count(*) > 1

**Comment by pedrogit** [comment]
Same issue with NFL:

WITH casid AS (
  SELECT cas_id
  FROM casfri50.nfl_all
  GROUP BY cas_id, layer
  HAVING count(*) > 1
)
SELECT DISTINCT left(cas_id, 4) inv
FROM casid;

BC10, NT02, AB06, BC08 and AB16 all produce duplicate CAS_ID, LAYER couples.

**Comment by pedrogit** [comment]
Make sure constraint 2.1, 4.1 and 5.1 pass in 01_addConstraint.sql on the final database before closing this issue.

**Comment by edwardsmarc** [comment]
DST issue needs to be re-tested using most recent table. 

Validation:
matchList(inventory_id, 'NB01'|-8886)

and translation:
copyInt(layer)

should result in a unique CAS_ID LAYER key.

**Comment by edwardsmarc** [comment]
SK02 duplicates in both LYR and NFL are due to two duplicated rows in the loaded data. Not clear why two ogc_fid's of the same value would be created. Investigating...

BC08 NFL issue might be due to an attribute mapping issue. Currently re-translating to test fix.

**Comment by edwardsmarc** [comment]
SK02 duplicates are due to two cases where the input wetland table has a duplicate row. When these are joined to the rest of the data using a LEFT JOIN it cause a duplication of the polygons.

Here is the current join code:
```
CREATE TABLE $fullTargetTableName AS
SELECT * FROM $tempTableName A 
LEFT JOIN $TableName_wetland I ON A.poly_id = I.poly_id_wetland;
```

And the proposed fix:
```
CREATE TABLE $fullTargetTableName AS
WITH I AS(
  SELECT wetland_veg, wetland_class, wetland_landform, poly_id_wetland 
  FROM $TableName_wetland 
  GROUP BY wetland_veg, wetland_class, wetland_landform, poly_id_wetland)
SELECT * FROM $tempTableName A 
LEFT JOIN I ON A.poly_id = I.poly_id_wetland;
```

This fix appears to remove the duplicate row. Now testing if it solves the issue...

**Comment by pedrogit** [comment]
Test 2.1 passed but not test 4.1 and test 5.1

**Comment by edwardsmarc** [comment]
I think the LYR duplicates for SK01 are caused by the ROW_TRANSLATION_RULE. Currently it always uses a notEmpty() call for the layer 1 species, even when translating layer 2. This results in an attempted layer 2 translation when there is no layer 2 info. LAYER therefore gets returned as 1 because there is only layer 1 info in countOfNotNull.
* I'll attempt to fix by changing ROW_TRANSLATION_RULE to use the species values for whichever layer is being translated. This should filter out the duplicate rows.

For NFL duplicates in NT02, the custom fvi01 countOfNotNull function is missing some NFL codes in the matchList call. Adding these should fix the issue.

**Comment by edwardsmarc** [comment]
Test 2.1, 4.1 and 5.1 now pass, but I've only loaded BC08, BC10, SK01 and NT02.
Need to test again once everything is loaded.

**Comment by pedrogit** [comment]
Reopening until constraint 2.1, 4.1 and 5.1 are tested over all the transtaled tables.

**Comment by pedrogit** [comment]
Constraints 2.1, 4.1 and 5.1 passed! Closing.
