### ISSUE TITLE
Photo year for SK06

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#317]
No photo year column in the source data. readMe of email exchange say: "That forest inventory was completed using photography from multiple years (from 1994-2005)".

What photo year was used in cas04 for this inventory? I checked the loading script but no values were assigned as far as I can tell.

Once resolved, add comment to SK06 loading scripts stating what the photo year is.

**Comment by edwardsmarc** [comment]
All SK_0006 rows in CASFRI 04 have photo_year of 1980.

@MelinaHoule can you confirm this is correct?

**Comment by MelinaHoule** [comment]
SK_0006 is Mistik.  1980 isn't correct. I 'll create a .txt straight away and put it in the folder inventory. My comprehension is we don't know the year per polygon. We have a range for the inventory. Here is the communication I had with Steve Reed back in 2015: 
-----------------------------------------------------
Dear Steve, 
I wrote you an email on April 10th about Mistik SFVI you sent to Dr. Steve Cumming on March 16th. I'm sorry to bother you with the same question, but we would need the year of photography of the inventory you sent us in order to process the data. 
Thanks for your support, 
Mélina Houle
---------------------------------------------------------------

Hi Melina,
That forest inventory was completed using photography from multiple years (from 1994-2005).  As far as a manual goes, there is a Saskatchewan Forest Vegetation Inventory specification manual on the Saskatchewan Government website. 
I believe it is newer than the spec used for the Mistik inventory, but should be quite similar.
Hopefully that helps.
Thanks,
Steve

**Comment by edwardsmarc** [comment]
I don't think we know the year per polygon either. I'm not sure how we should deal with a range of years. This would be a question for @pedrogit because it will impact the temporalization procedure.

**Comment by MelinaHoule** [comment]
It is not the only one like that. Some in AB have the same problem. The design in v4 was to indicate missing or unknown at the polygon level and the user was referring to the header table to extract the range at the inventory level. The user had to make the decision how to deal with that according to his needs, design, ...

**Comment by edwardsmarc** [comment]
I think this is a design issue related to the temporalization of the DB that we need @pedrogit to comment on.

I'll assign him this issue and we can resolve it when he is back.

**Comment by pedrogit** [comment]
1994-2005 is not such a huge time interval. If I had to choose a single year for temporalization I would go with 2000.
