### ISSUE TITLE
SK SFV01 - custom functions needed for 3 NFL attributes

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#334]
We need custom functions for NAT_NON_VEG, NON_FOR_ANTH, and NON_FOR_VEG. Each attribute is generated from 2 source attributes in a straight forward way.

NAT_NON_VEG

  - source attributes: nvsl, aquatic_class
  - mapText(nvsl, {'UK','CB','RK','SA','MS','GR','SB','WA'}, {'OT','EX','RK','SA','EX','WS','WS','LA'})
  - mapText(aquatic_class, {'LA','RI','FL','SL','FP','ST'}, {'LA','RI','FL','FL','BP','RI'})

NON_FOR_ANTH

 - source attributes: luc, transp_class
  - mapText(luc, {'ALA','POP','REC','PEX','GPI','BPI','MIS','ASA','NSA','OIS','OUS','AFS','CEM','WEH','TOW'}, {'CL','SE','FA','IN','IN','BP','IN','IN','IN','IN','IN','FA','SE','FA','FA'})
  - mapText(transp_class, {'RWC','RRC','TLC','PLC','MPC'}, {'FA','FA','FA','FA','FA'})

NON_FOR_VEG

  - source attributes: shrub1, shrub2, shrub3, herbs1, herbs2, herbs3
  - mapText(shrub1, {'Ts','Ls'}, {'TS','LS'})
  - mapText(herbs1, {'He','Fe','Gr','Mo','Li','Av'}, {'HE','NF','HG','BR','BR','HF'})

**Comment by edwardsmarc** [comment]
I don't think we need custom functions for these cases:

NAT_NON_VEG
* You can use 2 source attributes in mapText, put them in a string list. The source values will be concatenated together before the mapping. You can see the possible resulting values you need to map using
`SELECT DISTINCT CONCAT (nvsl, aquatic_class) FROM rawfri.sk02`
* Note the use of empty spaces in the source data instead of nulls, you need to account for that in the mappings because the space will be concatenated.

* Your function would look like this:
`mapText({nvsl, aquatic_class}, {'UK ','CB ','RK ','SA ','MS ','GR ','SB ','WA ', ' LA',' RI',' FL',' SL',' FP',' ST'}, {'OT','EX','RK','SA','EX','WS','WS','LA', 'LA','RI','FL','FL','BP','RI'})`

NON_FOR_ANTH
* Same thing.
`mapText({luc, transp_class}, {'ALA ','POP ','REC ','PEX ','GPI ','BPI ','MIS ','ASA ','NSA ','OIS ','OUS ','AFS ','CEM ','WEH ','TOW ', ' RWC',' RRC',' TLC',' PLC',' MPC'}, {'CL','SE','FA','IN','IN','BP','IN','IN','IN','IN','IN','FA','SE','FA','FA', 'FA','FA','FA','FA','FA'})`

NON_FOR_VEG
* I was thinking herb and shrub would be one layer each so we could have one big matchList call with all the mappings in the translation table. In the first NFL layer translation we would pass the shrub1 attribute, in the second layer we would pass the herb1 attribute (this is done in the attribute_dependencies table).
* Problem is the shrub translation above does not include all the possible values. There are generic tall and low shrub categories, but then there are specific species which can account for >80,000 rows in SK04. Can we assign each of these species into either tall shrub or low shrub? Maybe with SC's help?

Al Green/River Alder
Bh Beaked hazel
Ma Mountain maple
Sa Saskatoon berry
Pc Pin/Choke cherry
Cr High-bush cranberry
Wi Willows
Ro Prickly rose
Bi Bog birch
Bu Buffaloberry
Dw Red-osier dogwood
Ra Wild red raspberry
Cu Currant/Gooseberry
Sn Western snowberry
Bb Blueberry
Ci Shrubby cinquefoil
Bl Bog laurel
La Labrador tea
Le Leatherleaf
Be Bearberry
Lc Low-bush cranberry
Lb Lingonberry

**Comment by prvernier** [comment]
Can the matchList and notMatchList functions also take more than one attribute? For example
matchList({nvsl, aquatic_class}, {'UK ','CB ','RK ','SA ','MS ','GR ','SB ','WA ', ' LA',' RI',' FL',' SL',' FP',' ST'}

**Comment by edwardsmarc** [comment]
Yes!

**Comment by edwardsmarc** [comment]
List of possible concatenated values needs to be complete for each NFL. Needs to account for all inventories.

Custom countOfNotNull needed for layer and num of layers. Needs to run match list to see if there's an nfl layer, then run through countofnotnull with forest layers.

**Comment by edwardsmarc** [comment]
Generalise TT_avi01_stand_structure_translation for use in multiple inventories. Need to add a third layer option for SFVI.

**Comment by edwardsmarc** [comment]
Complete except for SK06

**Comment by edwardsmarc** [comment]
ME to add SK06 nfl codes to the custom countOfNotNull function.
