### ISSUE TITLE
Fix hard coded translations in casfri helper functions

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#359]
- 'CL' should not be used for DIST_TYPE. You can find it used in the translation rule in ab_avi01_dst.csv and nb_nbi01_dst.csv.

- 'UK' is also found as DIST_TYPE in the translated DST final table. I did not find it on my first search. I'll need the meaning.

- 'DW' is also found for NAT_NON_VEG. You can find it in yt_yvi01_dst.csv

- 'OT' is also found in the database for NAT_NON_VEG.

- 'P' is also found for WET_VEG_COVER

Also see list in Google Sheet.

**Comment by edwardsmarc** [comment]
The BC VRI translation includes a translation of source value 'AF' (alpine forest) in the 'non_productive_descriptor_cd' attribute to a NON_FOR_VEG value of 'AF' which does not exist in the CASFRI specs. 

All BC10 rows labelled AF have species info. I propose we drop AF from the NFL translation since the forest info is described in the LYR table.

**Comment by edwardsmarc** [comment]
DW occurs in VRI attribute 'non_veg_cover_type_1'.
It is translated to DW in CASFRI which is not a valid value.
DW is not listed in the VRI specs doc, but it does occur in the source data.

**Comment by edwardsmarc** [comment]
NB ECO translation has WET_LOCAL_MOD value of BP for beaver pond which is not in the CASFRI specs.

I'd guess the WET_LOCAL_MOD values are just pulled from source inventories so I don't see why we can't add BP to the specs.

The alternative is we drop this translation.

**Comment by edwardsmarc** [comment]
Any NFL UK (unknown) values should be caught with a validation function and returned as UNKNOWN_VALUE.

e.g. notMatchList(val, {'UK'} | UNKNOWN_VALUE)

**Comment by pedrogit** [comment]
> DW occurs in VRI attribute 'non_veg_cover_type_1'.
> It is translated to DW in CASFRI which is not a valid value.
> DW is not listed in the VRI specs doc, but it does occur in the source data.
> 
> @prvernier - any idea what DW represents?

In the yt_yvi01_dst.csv table 'DW' gets translated to 'WF', but it is still not translated in the helperFunctionsCASFRI.sql function. So there is only need to update the function.

**Comment by prvernier** [comment]
Looks like DW = windthrow in the Yukon manual. This is translated to the CAS code WF (windfall - blow down).

**Comment by prvernier** [comment]
In BC, DW = down dead wood.

**Comment by pedrogit** [comment]
Here is what I found:

1) "CL" is a disturbance type source value for two source inventories: 

- In AB "CL" means "Clearing (extent not required)" and is translated to "OT" (OTHER) in CASFRI
- In NB "CL" means "Plantation cleaning" and it is translated to "SI" (Silviculture Treatments - Planting, Thinning, Seed Tree) in CASFRI
- "CL" is still found as a translated value in AB16 from the "CU" value.
 
2) "DW" is also a disturbance type that must be tranlated to "WF" but it is still translated to "DW" in the YT02 translation table.

   In BC "DW" is also translated to "DW" by the TT_vri01_nat_non_veg_translation() function but it is not a valid CASFRI value for the NAT_NON_VEG attribute. 

3) "UK" is the translation of the first letter of the line_7b_disturbance_history BC source attribute (e.g. "N36", "N13"). N is not documented in the BC dictionary. Maybe Sighir would know it's meaning? According to Pierre V "UK" was added by Steve C. Suppositly means "UNKNOWN". Steve or Melina could probably answer. 

"UK" is also a NT, a AB source value that is translated to "UK" for DIST_TYPE. In both cases, if "UK" means "UNKNOWN", it should be translated to CASFRI error code UNKOWN_VALUE either by a notMatchList(val, {'UK'} | UNKNOWN_VALUE) validation rule or by a target value in the translation function. I think the right translation is better since it does not involve an addition validation rule and that UK is a valid source value.

"UK" is also a SK SFVI source value meaning UNKNOWN. It should be translated to CASFRI UNKNOWN_VALUE.

4) "OT" is listed as a target code for NAT_NON_VEG in the NB and the SK_SFV translation tables but it is not a valid CASFRI NAT_NON_VEG code.

"OT" is also listed as a target code in SK_UTM for NON_FOR_VEG in the SK_UTM translation table but it is not a valid CASFRI NON_FOR_VEG code.

5) "P" as a wrong WET_VEG_COVER code was fixed.

Those values must be checked in the specification, in the translation tables, in the CASFRI Helper Function and in the constraints added to the final database.

**Comment by pedrogit** [comment]
Make sure constraints 2.19 and 3.13 pass in 01_addConstraint.sql on the final database before closing this issue.

**Comment by pedrogit** [comment]
Remains 1c, 3b, 3c, 4a, 4b.

**Comment by pedrogit** [comment]
Test 2.19 passed (actually now does not pass because of #386).

**Comment by pedrogit** [comment]
All related tests passed (and were replaced by other issues). Closing.
