### ISSUE TITLE
Should NFL attributes always be reported on different CASFRI rows?

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#365]
In some inventories such as SK-SFVI, there is shrub and herb information with associated coverage or height for each. These are reported in the NON_FOR_VEG attribute. There is also other NFL info for NON_FOR_ANTH and NAT_NON_VEG. This structure requires 3 separate NFL translations as 3 different layers, one for shrub, one for herb, and one for NON_FOR_ANTH/NAT_NON_VEG. In this example, the last layer will be either NON_FOR_ANTH or NAT_NON_VEG, never both.

In other cases where coverage and height info is not available, we report all three NFL attributes using a single translation, and they therefore appear together in a single NFL layer. BC is an example of this where most NFL rows will report one of the three attributes, but in many cases two are reported in the same row, in rare cases all three. **The question is, should these be processed as separate translations in the workflow and each be assigned a unique layer number?**.

Put another way, should herbs and shrubs always be in a different layer to lakes and rivers. And should agriculture and industry always be in a different layer to herbs, shrubs, lakes and rivers?

**Comment by pedrogit** [comment]
The problem comes (again) from the model which implies that NON_FOR_VEG, NON_FOR_ANTH and NAT_NON_VEG are always mutually exclusive and can be modeled in the same row. As soon as two stand components are of the same nature (e.g. NON_FOR_VEG) the model force you to either ignore one of them or store them in different rows. The new model eliminate this problem by allowing only one component per row, as many components as necessary per stand. No choice.

We already support many NFL rows per stand. If we allow many in the same row then we end up with a mixed solution where some are modelled on many rows and some others are modelled in the same row. What determines if the data goes into one or many rows? Is it how the source data is structured or is it just that as soon as two components are of the same NFL nature they go in different rows? That seems arbitrary to me.

I guess all NFL components on different rows is a better, more general and substainable solution. How do we assign STRUCTURE_PER and CROWN_CLOSURE when there is only one value for two component in this case? Does STRUCTURE_PER has to sum up to 100%? Probably it does not have to...

**Comment by edwardsmarc** [comment]
STRUCTURE_PER is just copied from the source when it's available. It's generally only included for H stands.

We should add a validation check that no single row has 2 NFL attributes, it can be difficult to test this during development.

**Comment by edwardsmarc** [comment]
This only effect's BC.

All other inventories either already have nfl attributes translated on separate rows, or nfl is a single source attribute so there will only ever be one of the three nfl attributes per row. Or in some cases there are multiple attributes, but only one NFL attribute ever gets translated.

**Comment by edwardsmarc** [comment]
ROW_TRANSLATION_RULE NFL helper function needed to avoid LAYER = 0 rows in the NFL translations.

e.g. in BC and SK, each NFL attribute translated into different CASFRI rows, but the ROW_TRANSLATION_RULE passes if any NFL info is present. The ROW_TRANSLATION_RULE needs to be specific to the NFL attribute being processed.

TT_HasNFLInfo()
* takes inventory_id
* takes a stringList of NFL attribute names (e.g. {'non_for_veg', 'nat_non_veg', non_for_anth'})
* Function calls the validations for the requested attributes.
* e.g. TT_HasNFLInfo('BC08', {'non_for_veg'}) would only return TRUE if the non_for_veg translation for BC will return a valid value.

**Comment by edwardsmarc** [comment]
This function is also need for SK. Most cases have only one NFL attribute per row but it is possible to have multiple. SK will need to filter using two NFL attributes. i.e. the translations either run non_for_veg, or they run nat_non_veg and non_for_anth together.

**Comment by edwardsmarc** [comment]
This should fix the duplicate bc08 rows in #305

**Comment by pedrogit** [comment]
FYI test 5.16 was modified to allow LAYER = 0

**Comment by pedrogit** [comment]
Make sure to add TT_HasNFLInfo() to the uninstall script.

**Comment by edwardsmarc** [comment]
Passing of constraints in #305 means this issue is complete.
