### ISSUE TITLE
Review the LAYER description in the specifications

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#373]
What happens with V?

Explain the meaning of 0.

**Comment by edwardsmarc** [comment]
Based on #253 the only inventory that could have V is BC08 where we agreed to copy the layer_id from source data instead of using CASFRI derived method for LAYER (I'm working on completing #253 today). I'll update the specs to reflect this.

In what scenario is LAYER = 0 acceptable? When there's DST but no LYR or NFL?

**Comment by edwardsmarc** [comment]
Note that in BC08 there is a layer_id value S that occurs on 5 rows. S stands for Silviculture.

**Comment by edwardsmarc** [comment]
LAYER = 0 is related to #230.
