### ISSUE TITLE
Get rid of * in species codes

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/CASFRI#380]

**Comment by MelinaHoule** [comment]
I asked Steve about the *. From what he remembered, the * was used to indicate error or code to validate. It is a regular expression to tell the perl script not to read the line. All lines with remaining * should be deleted. The species list was verified by Steve at that time and remaining * are errors. Benedicte never went back and deleted them, since anyway those lines were not read by the Master perl script.

**Comment by edwardsmarc** [comment]
Checked there are no more * in species_code_mapping. Closing
