### ISSUE TITLE
SK SFV01 NFL table needs to be revised 

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#390]
The aquatic_class source attribute is currently one of two attributes used to populate the NAT_NON_VEG attribute. However, two of its values are anthropogenic and should be removed and added to the NON_FOR_ANTH attribute, alone or in combination with one of the other identified source attributes. In practice, this means:
1. Removing the 'WAFP' value from the source list in the translation of NAT_NON_VEG
2. Adding the aquatic_class source attribute as a third attribute used to translate the NON_FOR_ANTH attribute
3. Adding the 'WAFP' value to the source list for the NON_FOR_ANTH attribute
4. Adding 'DI' (another anthropogenic value from aquatic_class) alone or in combination to the source list for the NON_FOR_ANTH attribute

**Comment by prvernier** [comment]
Note that this affects the SK04 and SK05 inventories / translations.

**Comment by pedrogit** [comment]
And should aquatic_class stay as a source attribute for NAT_NON_VEG? Or it should be removed?

**Comment by prvernier** [comment]
aquatic_class should be used for NAT_NON_VEG (lake, river, flooded land, seasonal floods) and NON_FOR_ANTH (ditch, flooded pit).

**Comment by pedrogit** [comment]
@prvernier No 4 letter codes ('WASF', 'WALA', 'UKLA', 'WARI', 'WAFL', 'WAFP', 'WAST') can be found in the source attribute corresponding to nvsl, aquatic_class and np of any SK source inventory. Should they really be in the translation of NAT_NON_VEG? They seems to be the concatenation of two other codes. e.g. 'WASF' is the concatenation of 'WA' and 'SF'. That does not make sense to me...

**Comment by edwardsmarc** [comment]
The problem here was that we had NFL mappings from two source attributes. Rather than making a custom function to deal with this we used mapText(). If a stringList of values is given to mapText it concatenates them together before running the mapping. We used this basically feed values from two source attributes into one translation function. It worked well because in most cases when nvsl had a value, aquatic_class was empty and vice versa. So the results of the concatenation was just the value for the non-empty attribute. Unfortunately in some rows there were values for both attributes which led to the four letter codes you see in the table. In these cases only one of the codes is a valid translation.

**Comment by pedrogit** [comment]
@prvernier Note that "DITCH", to which "DI" should be translated, is not in the specification. Should we add it to the spec or should we translate "DI" to something else?

**Comment by prvernier** [comment]
I guess DI was missed. I would agree, the closest seems to be BORROW_PIT.

**Comment by prvernier** [comment]
Earlier in this issue, it was suggested that we add the aquatic_class attribute as the third source attribute for translating NON_FOR_ANTH, specifically to translate the values "DI" and "FP" to "BORROW_PIT". Will @pedrogit do this or should I?

**Comment by pedrogit** [comment]
It's done already. I just need to test and commit.

**Comment by pedrogit** [comment]
Check constraints 5.22 and 5.23 before closing.

**Comment by pedrogit** [comment]
Constraints 5.22 and 5.23 applied without problem during last complete translation. Closing.
