### ISSUE TITLE
QC03 disturbances are split into 2 attributes: Need DST helper function to order dist_1 and dist_2 chronologically

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#394]
Quebec uses 2 columns for disturbance: origin (> 75% of the polygon has been disturbed) and perturb (25-75% of the polygon has been disturbed). Need helper function to verify which one came first when the 2 types of disturbance happen within the same polygon.

The rule to order DST is : the oldest event described first

**Comment by edwardsmarc** [comment]
So we have two disturbances each with a year, and we need to assign the earliest disturbance as dist_type_1 and the more recent disturbance as dist_type_2?

I think we could do this with four new helper functions added to the engine:

tt_minInt(stringList)
This would return the smallest value from the list and would be used for dist_year_1

tt_maxInt(stringList)
This would return the largest value from the list and would be used for dist_year_2

tt_minIndexText(stringList, stringList)
This would calculate the index of the smallest integer in the first list, and return the corresponding string matching the index in the second list. This would be used to assign the disturbance for dist_type_1.

tt_maxIndexText(stringList, stringList)
Same but returns the index of the max value. This would be used to assign the disturbance for dist_type_2.

**Comment by MelinaHoule** [comment]
What would happen if the year of disturbance is missing? Would the disturbance type be dropped. 

I'm doing an attempt to write a special helper function. My plan was:
1- to map the disturbance for translation (TT_MapText)
2- identify number of disturbance
3- When 1 dist: used the mapped translation in dist_1
4- When 2 disturbances, determine _old_dist and _new_dist and mapped translation

Does that make sense? Or we could make it more generic using your way @edwardsmarc ?

**Comment by edwardsmarc** [comment]
If the year was missing we could decide what to do. Options could be to catch missing years with a validation function and return an error code, or to always return disturbance codes with missing years as the earliest or latest disturbance for the polygon. Normally if the year is missing we still report the disturbance type if we have one and we record the year as UNKNOWN_VALUE.

I'm not sure which way is better, I'll have to review your code and think about it. Usually we avoid using custom helper functions unless we really need to, it's better to have the translation rules visible in the translation tables. But if the logic is very complex its better to write a custom function and then explain the logic in the description column of the translation table.



@edwardsmarc will add @MelinaHoule 's sql code to the helperFunction script. The following input attributes are used:
"origine" : disturbance affecting >75% of the polygon;
"an_origine" : year of the origine disturbance;
"perturb": disturbance affecting 25-75% of the polygon;
"an_perturb": year of the partial disturbance.

**Comment by edwardsmarc** [comment]
The following details what would be required to develop generic helper functions to do the QC03 DST translations. Benefits of this method over writing custom helper functions are: 1) it keeps the translation rules and validation rules in the tables rather than hidden in the code, 2) the new functions could be useful in other inventories.

I think this generic method would take a bit longer to code, but probably less time to edit in the future if we need to make corrections.

**Scenarios**
All possible cases of the 4 input values and the CASFRI values that would be returned. Using example disturbances of a burn in 1990 and wind damage in 2000:
| origine | perturb | an_origine | an_perturb | DIST_TYPE_1 | DIST_YEAR_1 | DIST_TYPE_2 | DIST_YEAR_2 |
| -------- | -------- | ----------- | ----------- | --------------------- | ------------------- | -------------           | --------------- |
| burn     | wind     | 1990         | 2000         |       burn                   |       1990               |  wind                     |     2000            |
| burn     | null      | 1990         | null            |       burn                   |       1990               | NOT_APPLICABLE | NOT_APPLICABLE |
| null      | wind     | null           | 2000          |       wind                   |       2000                | NOT_APPLICABLE | NOT_APPLICABLE  |
| burn      | wind     | null           | 2000         |       wind                  |       2000                 |    burn                 | UNKNOWN_VALUE |
| burn      | wind     | null           | null           |       burn                  | UNKNOWN_VALUE |    wind                | UNKNOWN_VALUE |
| null       | wind     | 1990           | 2000       | UNKNOWN_VALUE | 1990                       |    wind                | 2000                        |
| null       | wind     | 1990           | null         | UNKNOWN_VALUE | 1990                       |    wind                | UNKNOWN_VALUE |

**New generic helper functions**
All functions would have an argument setNullTo which would assign an integer to any NULL years. We would assign this to 9999 so NULLs are always considered the most recent disturbance.
* tt_max({1990, 2000}) -- returns 2000 - return max value.
* tt_min({1990, 2000}) -- returns 1990 - return min value.
* tt_minIndex({1990, 2000}) -- returns 1  - Return the index of the smallest value. In cases with multiple smallest values, return the lowest index. Used in the following functions.
* tt_maxIndex({1990, 2000}) -- returns 2  - Return the index of the largest value. In cases with multiple largest values, return the lowest index. Used in the following functions.
* tt_minIndexCopyText({1990, 2000}, {a, b}) -- returns a - return the value from the second list matching the index of the smallest value from the first list.
* tt_maxIndexCopyText({1990, 2000}, {a, b}) -- returns b - return the value from the second list matching the index of the largest value from the first list.
* tt_minIndexMapText({1990, 2000}, {a, b}, {a,b,c,d}, {aaa, bbb, ccc, ddd}) -- returns aaa - Run mapText using the value from the second list matching the index of the smallest value from the first list.
* tt_maxIndexMapText({1990, 2000}, {a, b}, {a,b,c,d}, {aaa, bbb, ccc, ddd}) -- returns bbb - Run mapText using the value from the second list matching the index of the largest value from the first list.
* tt_minIndexNotNull({1990, 2000}, {null, b}) -- returns FALSE - Run notNull() on the value in the second list matching the index of the smallest value in the first list.
* tt_maxIndexNotNull({1990, 2000}, {null, b}) -- returns TRUE - Run notNull() on the value in the second list matching the index of the largest value in the first list.

**translation rules and descriptions**
* **DIST_TYPE_1 validation**
  * tt_notEmpty({origine, an_origine, perturb, an_perturb}, any=TRUE) - If any attributes have info then we have a dist_1.
  * tt_minIndexNotNull(stringList, stringList|UNKNOWN_VALUE) - Check if we have a dist_type_1 value, it could be null if only year present, in which case return UNKNOWN_VALUE.
* **DIST_TYPE_1 translation**
  * tt_minIndexMapText() - get the disturbance value with the oldest year and run it through mapText.
* **DIST_YEAR_1 validation**
  * tt_notEmpty({origine, an_origine, perturb, an_perturb}, any=TRUE) - If any of the 4 attributes have a value, we know there is dist_1.
  * tt_notEmpty({an_origine, an_perturb}, any=TRUE|UNKNOWN_VALUE) - If one year, it will always be assigned dist_1. If two years, smallest becomes dist_1. Catch the case where both years are null and return UNKNOWN_VALUE.
* **DIST_YEAR_1 translation** 
  * tt_min(an_origine, an_perturb) - always take the smallest year for dist_1
* **DIST_TYPE_2 validation**
  * tt_hasCountOfNotNull({origine, an_origine}, {perturb, an_perturb}, 2|NOT_APPLICABLE) - Needs type or year from both slots to have a second disturbance.
  * tt_notEmpty({origine, perturb}, any=FALSE|UNKNOWN_VALUE) -  If we have second disturbance but the second type is null, return UNKNOWN_VALUE. This means we only have year for the second disturbance.
* **DIST_TYPE_2 translation**
  * tt_maxIndexMapText() - get the disturbance value with the highest year and run it through mapText.
* **DIST_YEAR_2 validation** 
  * tt_hasCountOfNotNull({origine, an_origine}, {perturb, an_perturb}, 2|NOT_APPLICABLE) - Needs type or year from both slots to have a second disturbance.
  * tt_notEmpty({an_origine, an_perturb}, any=FALSE|UNKNOWN_VALUE) -  If we have second disturbance but second year is null, return UNKNOWN_VALUE. This means we only have type for the second disturbance.
* **DIST_YEAR_2 translation**
  * tt_max(an_origine, an_perturb) - always take the largest year for dist_1

**Comment by MelinaHoule** [comment]
Great!!!!

What if both distrubance have year = NULL? Which one would be picked first?

**Comment by edwardsmarc** [comment]
If both years are null, we would return origine as dist_1. Is that the correct behavior?

**Comment by edwardsmarc** [comment]
@MelinaHoule - There is a specific behavior in minIndexMatchList and maxIndexmatchList (and minIndexNotNull and maxIndexNotNull) that we need to document in the description column of the translation table for DIST_TYPE_1 and DIST_TYPE_2:

When the years of the two disturbances match, or when both are null, we need minIndexNotNull and maxIndexNotNull to return  different disturbances. For example in the case where we have a burn in 1990 (origine) and wind throw in 1990 (perturb), we need minIndexNotNull to return burn, and maxIndexNotNull to return perturb.

For this reason in the case where there are multiple indexes matching the min or max value (in our example, indexes 1 and 2 both match the min/max value of 1990), minIndexNotNull will always return the first index, and maxIndexNotNull will always return the last index.

This should be clearer when you read the documentation for the new functions (I'm adding this now and will then push the code updates). It might also be helpful for you the review the unit tests I added to the helperFunctionsTest.sql for these functions. I used the test cases in the table above for the unit tests.

**Comment by edwardsmarc** [comment]
Note all minIndex and maxIndex functions have been updated so that in cases where there are matching years, instead of always returning the first or last matching value, they now return the first or last not null value. This ensures correct behavior in scenarios 11-14 in the table above.
