### ISSUE TITLE
CASFRI Height Translation Issues

### ISSUE THREAD

**Issue by sgautam2076** [edwardsmarc/CASFRI#462]
Here are a few height translation  issues that I noticed while looking at forest resource inventory acquired from Ontario.
1.	Oht (i.e., over story height) and uht (i.e., understory height) values lower than 1m: There are height measurements less than 1 m in Ontario data. It seems in CASFRI height is only considered if it is => 1m. In this case, it would be nice to capture height less than 1m and do not left out such information in the CASFRI translation.

2.	Oht (i.e., over story height) is null but uht (i.e., understory height) have values: I realized CASFRI already populated uht as oht, which sounds good to me. However, I am wondering if there is any supporting documents or communication with data provider suggesting this fix. If so would be nice to refer in our documentation.
 
3.	Oht is 0 but uht have values: In this case, CASFRI has treated differently than it was treated when oht is null (as mentioned in second point). I think it would be nice to treat similar way (because 0 or NULL seems same to me in this case as we don’t measure height 0).

4.	Oht is lower than uht: I do not see the situation this may occur (unless there is specific measurement protocol). But there are cases in the FRI data (Ontario) that we have. I see this could be more of data quality issues and I do not think fixing this issue is within the scope of this project at the moment. At lease, if we can raise some flag for such situation (if possible) would be good, but not sure if this can be doable. Do you have any thoughts about handling this in CASFRI?

Thank you!

**Comment by edwardsmarc** [comment]
1 - Good point, the specs state height can be between 0 - 100 m so I've updated all the height validations to allow this range. I've specified that the height must be greater than zero, so a value of zero will still produce an error code.

2 - The assignment you describe is achieved through the CASFRI use of LAYERs. We determine the presence of LAYERs in ON01 for a given polygon using the species composition code. 
  - If oscomp has a value then we know there is an overstory layer. 
  - If uspcomp is present then we know there is an understory layer. 
  - If both layers exist, the overstory layer gets assigned LAYER = 1 and the understory gets assigned LAYER = 2. 
    - In this case LAYER 1 height would be oht and LAYER 2 height would be uht. 
  - If there is no overstory layer present then the understory gets assigned LAYER = 1 (we always assign LAYER value sequentially starting at 1, using the layers that are present for a polygon). 
    - In this case LAYER 1 would have height uht.

3 - oht can be NULL or zero. These values will be caught during validation and would return NULL_VALUE and OUT_OF_RANGE respectively. In order to treat zero as a null value I will add another validation to catch the zero's and report them as NULL_VALUEs.

4 - The only way to check LAYER 1 height is > LAYER 2 height would be to add a constraint. Constraints are used to validate the translated data and make sure it conforms to the specs. The only way I can think of to flag the problem rows would be to query the translated CASFRI database. Maybe @pedrogit has another idea? I've added #463 that describes this problem in more detail.


**ACTION - @edwardsmarc to catch zero's as NULLs**
**ACTION - @edwardsmarc to check that the CASFRI LAYER assignment is well described in the CASFRI readme and specs**

**Comment by pedrogit** [comment]
Don't forget to update the constraints.

**Comment by edwardsmarc** [comment]
@pedrogit - none of the height constraints need to be updated. And I don't think we can add a layer constrint until we fix #463

**Comment by edwardsmarc** [comment]
Based on #463 we are moving toward CASFRI heights having to be in order from layer 1 being the tallest. We will need to add a constraint to check that all LYR layer heights are in order. I'm closing this issue and will request the constraint in #463.
