### ISSUE TITLE
PC02 - NFL translation and LAYER

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#501]
PC02 has a horizontal structure. According to the manual, each polygon can have up to 7 layers. Each layer has a structure percent assigned. Within a layer, LYR and NFL do not use the same field and they are not mutually exclusive. For example,  if layer 1 is defined as willow-alder thicket, we would get a NFL value (v1pcm = 7) translated as TALL_SHRUB but by looking at the LYR field (v1sp1, v1sp2, v1sp3, v1sp4), we will get species such as willow and alder, thus a line in LYR will be created. 

How to assign LAYER? Does that mean we consider 14 possible layer in PC02? How to assign STRUCTURE_PER if LAYER =1 with STRUCTURE_PER = 60% is a combinaison of LYR and NFL?

**Comment by edwardsmarc** [comment]
I don't think we want to record the same information in both LYR and NFL. Either the layer is forested OR it is non-forested. It can't be both. So we should decide whether willow and alder is a LYR or NFL and just report it in one of the tables. Are there other cases like this? Maybe we can list them in this issue and decide how to treat each one?

We will have to figure out how to avoid reporting that information in the other table. We can probably use the ROW_TRANSLTION_RULE to do that. That rule will run some logic that decides if the record is LYR or NFL. 

I think you are correct that we will now need to have 14 rows in the attribute_dependencies table. 7 for LYR and 7 for NFL since each of the 7 layers could be either LYR or NFL. This is similar to how the AB rows are set up (there are only 2 possible layers but each layer could be LYR or NFL so we have 4 rows in attribute_dependencies).

**Comment by MelinaHoule** [comment]
Another complication:

Lake is derived from a field given at the polygon level (shrln) while other NFL values such as HERBS, LOW_SHRUB, TALL_SHRUB, GRAMINOID and EXPOSED_LAND are derived from field given at the layer level within the polygon.  In NFL table, we translate STURCTURE_PER at the layer level. STURCTURE_PER is found in the source data. Most of the polygons described as LAKE (162/164) have no layer description. The entire polygon seems to be LAKE. I think we can assume structure_per =100%. But 2 polygons defined as LAKE  have also layer defined. The first polygon has 5 layers (all layers have tree species (black spruce, poplar, ...)), the other polygon has 4 layers representing NFL values (graminoid, low shrubs,...). In those 2 polygons, the sum of structure_per of all layer = 100%. I don't know where LAKE fall into that polygon. 

How to translate NFL? 

Should this be a new issue or should we add a layer when that happen? How to deal with structure_per if we add a layer?

**Comment by edwardsmarc** [comment]
I think the best way to fit your example into the schema would be to have the 5 layers described as normal with their STRUCTURE_PER summing to 100%. Then we could add a sixth layer  for the LAKE with STRUCTURE_PER = UNKNOWN_VALUE.

We would need to add a new row to the attribute_dependencies just for translating the LAKE polygons. So there would 8 NFL rows in attribute_dependencies (even though we will never actually get all 8 in the same polygon).

For the translations I think you could use mapTextNotNullIndex() again with indexToReturn set to 1. That would let you add the LAKE mapping to the regular NFL mapping in one translation function. Something like:
`mapTextNotNullIndex(lake_att, {lk}, {LAKE}, nfl_att, {a, b, c}, {TALL_SHRUB, LOW_SHRUB, GRAMINOID}, 1)`
For the 7 NFL rows in attribute_dependencies you would map the NFL layer being translated and set lake_att to NULL. For the 8th row you would set nfl_att to NULL and map lake_att to shrln.

I guess we'd need a custom function to assign STRUCTURE_PER = 100% when the entire polygon is LAKE.
