### ISSUE TITLE
PC01 - Does the schema support vertical information within a horizontal structure

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#510]
In PC01, polygons have a horizontal structure. Each polygon can have up to 3 forested components and 3 non-forested components. Layer is assigned according to the number of component found within the polygon. However, each forested component can have overstory and understory information (vertical structure). Overstory and understory have respective height, density and age class. 

How to translate vertical information in a horizontal structure? I don't think the actual schema allows to support verticality within a horizontal structure. 

PC01 has 8094 polygons. Only 64 have vertical structure. If we want to keep as much information as possible, we could translate understory as species_2, but we would loose information on height, density and age class.

**Comment by edwardsmarc** [comment]
You're correct, current schema only allows a polygon to have horizontal or vertical structure, not both (new schema would support this).

Maybe we just have to drop the understory information for those 64 cases? We should record that we dropped them in the description column for STAND_STRUCTURE in the translation table (and maybe in the specs somewhere).

I don't like using species_2 because that's not how the data were recorded in the source table.

[If we decide to drop the understory info, leave this issue open until we have recorded that we dropped the info in the translation table and in the specs]
