### ISSUE TITLE
PC01 - LYR Need custom function to translate SPECIES

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#512]
In PC01, species value are concatenated into the same field per layer. All species values use 2 characters. We will need a function to split species prior to use the species_code_mapping to translate. 

I think this is the same logic as QC04, but instead of reading qc_species_code column, we would need to refer to pc01_species_codes column. 

Should we change  qc_prg4_lengthMatchList and qc_prg4_species_translation to make them more generic?

**Comment by edwardsmarc** [comment]
qc_prg4_species_translation was a special case because we fits had to edit the string if it started with a double species entry.

I think for PC01 we could use TT_LookupTextSubstring(). It takes a substring and maps the resulting string using the lookup table.

For species_1 we would use: LookupTextSubstring(species_1, 1, 2, 'translation', 'species_code_mapping', 'pc_species_codes', 'casfri_species_codes')
For species_2: LookupTextSubstring(species_1, 3, 2, 'translation', 'species_code_mapping', 'pc_species_codes', 'casfri_species_codes')
For species_3: LookupTextSubstring(species_1, 5, 2, 'translation', 'species_code_mapping', 'pc_species_codes', 'casfri_species_codes')

**Comment by MelinaHoule** [comment]
Clode with commit ca64aee9885c6914c1b72f5e0bc8eabb581dd04c

**Comment by edwardsmarc** [comment]
FYI you can use MatchTableSubstring as the matching validation function to make sure the substring is in the lookup table

**Comment by MelinaHoule** [comment]
Yes, I did. I used NL as an example.
