### ISSUE TITLE
AB25 source files have different schema

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#518]
AB25 folder contains 3 files covering 3 non-overlapping areas:

AVI_CROWN
s7w11_n830
p1_twp

AVI_CROWN has different attributes. For example, it has no trm attribute (used for mapheet_id), and it has a photo_year column (other files would require an intersection to get photo_year).

I am wondering if these should be split into two datasets or merged into one during loading.

@MelinaHoule what was done in CAS04? I can't tell from looking at the old python scripts.

**Comment by edwardsmarc** [comment]
If these need to be merged into one file during loading, take the following steps in the -sql line:

- area column for s7w11_n830 and p1_twp should be renamed shape_area
- photo_yr should be set to NULL for s7w11_n830 and p1_twp

**Comment by MelinaHoule** [comment]
AB25 shouldn't be as listed above. AB25 is AVI_CROWN only. It was downloaded from a ftp site in 2012. Prior to 2012, we used an older version of AVI (AB01) that was splitted by FMAs (each FMA had their own shapefile). In 2012, when we got the new AVI_CROWN, the structure was different. All FMAs were found into one shapefile (AVI_CROWN.shp). We realized that 2 FMAs were missing from the prior2012. That means the coverage of the new2012 was smaller than the one prior2012. In order to maximize the FRI coverage, we moved the 2 FMAs found in prior2012 into the new CROWN. So, s7w11_n830 and p1_twp was part of the AB01.  I guess they should be called that way.

**Comment by edwardsmarc** [comment]
Translating AB01 is not currently a deliverable. According to the inventory_list, it was not included in CASFRI v3 or v4. Issue #505 lists the AB inventories that we agreed to translate before March 31st. They include all the government inventories from CASFRI v4. I am assuming AB25 replaced some of those older inventories which is why they were dropped for CASFRI v4?

I think we should add AB01 to the list in #505 since it appears to add new coverage not captured in AB25.

**Comment by MelinaHoule** [comment]
AB25 was supposed to be the same as AB01, but with a little bit more coverage, more info for each polygons and presence of photoyear. They represent the same inventory. That is why when we got AB25, we dropped AB01. AB01 did not bring any historical background. AB01 is older for ACQUISITION_DATE, but not for PRODUCTION_DATE. The province was not able to explain why 2 FMAs were dropped when they merged their dataset.
