### ISSUE TITLE
Make index for qc stand structure lookup table in all qc workflow scripts

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#533]

**Comment by edwardsmarc** [comment]
@pedrogit - is it best to add one index that can be used by multiple workflow scripts, or create a different index for each script?

For example, qc_standstructure_lookup is used in the lyr.sql, cas.sql and nfl.sqp scripts. 

Should each script create it's own index (e.g. qc_standstructure_idx_lyr, qc_standstructure_idx_cas, qc_standstructure_idx_nfl)? 

Or can the index name be the same in all three scripts (e.g. qc_standstructure_idx)?

**Comment by pedrogit** [comment]
It's better to try to create the index in each script in case we have to run any of them by themselve. Otherwise we would have to search for the CREATE INDEX statement. Each script on the same level have to be self sufficient.

To avoid regenerating the index if it already exists, name them the same and add "IF NOT EXISTS" in the CREATE INDEX statement.
