### ISSUE TITLE
ON - FIX CAS_ID creation to incorporate map_id argument

### ISSUE THREAD

**Issue by MelinaHoule** [edwardsmarc/CASFRI#536]
In Ontario, the creation of CAS_ID uses xxxxxxxxxx as a filler for map_id and POLYID as polygon_id argument. The length of POLYID exceed 10 character which do not allow us to store all the information. The user would not be able to retrieve the source polygon using the CAS_ID. 

In the source data, POLYID is built using the concatenation of map_id, dash and unique_id. By spliting POLYID using the dash will allow us to recover map_id and polygon_id arguments and solve the length issue we have for polygon_id.

**Comment by edwardsmarc** [comment]
polyid is not standardized throughout the dataset. For example here are a selection of values:

156805480-9910252
175705390-0490-12
15265055450-29259aa
167205230-1098
6353294021

Splitting using '-' won't work because some values have zero dashes, some have more than one, and in some cases there are more than 10 characters before the '-'.

I propose we create two new id columns during loading named polyid_1_10 and polyid_11_20. 
polyid_1_10: characters 1 - 10 of polyid
polyid_11_20: characters 11 - 20 of polyid.

We would use these two attributes as the last two cas_id values. The longest polyid has 19 characters so no values will be trimmed. Users could trace back to the source data by concatenating these two values back together and dropping any of the padding characters (leading 0's or x's).

**Comment by edwardsmarc** [comment]
Be sure to document the approach in the translation table description.

**Comment by pedrogit** [comment]
Is there another attribute that we could use as unique id? Sometimes there is more than one unique identifier.

**Comment by edwardsmarc** [comment]
No, ON02 only has polyid.

**Comment by MelinaHoule** [comment]
I don't see any other field that could be used instead of POLYID.  If we apply Marc proposition, we will end up using the map_id argument to store non map_id information. i don't think it matters if documented, but I still want to raise the question

**Comment by edwardsmarc** [comment]
Note on top of @MelinaHoule comment. We would be using the map_id slot in the cas_id to store non map_id information.

There is also the MAP_SHEET_ID attribute in the CAS table, which is currently NOT_APPLICABLE because no mapsheet value is reported in the source data.

Seems like we either need to relax the definitions for the cas_id slots, or increase the number of characters to 20 to accomodate polyid.

**Comment by edwardsmarc** [comment]
Edit documentation to state casid is made up of a primary and secondary unique id, instead of using map sheet id terminology.
