### ISSUE TITLE
Issues on CASFRI Crown Closure Translation (New Brunswick)

### ISSUE THREAD

**Issue by sgautam2076** [edwardsmarc/CASFRI#549]
I am not quite sure about CASFRI translated Crown Closure values for a few plots and looks strange to me (see the attached file for related issues). Hence, I am creating this issue.
[Issues on CASFRI Crown Closure Translation_NB.docx](https://github.com/edwardsmarc/CASFRI/files/5873987/Issues.on.CASFRI.Crown.Closure.Translation_NB.docx)

**Comment by edwardsmarc** [comment]
## Q1
The issue here is that there is no species info in the source table for layer 1. But there is species info for layer 2. You can see using:

```
SELECT l1s1, l1s2, l1s3, l1s4, l1s5, l1cc, l2s1, l2s2, l2s3, l2s4, l2s5, l2cc FROM rawfri.nb02 WHERE poly_id = 232832 AND ogc_fid = 485744
```
The only info for layer 1 is the crown closure value of 4. If you look at the ROW_TRANSLATION_RULE in the translation table, it only translates rows that have species values. So in this case, layer 1 is getting dropped because it has no species values, and layer 2 in the source table is getting assigned as layer 1 in CASFRI. This is why you get '0 rows' when you search for CASFRI layer 2.
If you think we should be including the first layer in CASFRI we could easily do that by adding the crown closure values to the ROW_TRANSLATION_RULE. You would end up with a LYR LAYER 1 row with all null values except for CROWN_CLOSURE_UPPER and CROWN_CLOSURE_LOWER. And source layer 2 would become CASFRI LAYER 2.

## Q2
I think this is the same issue.
The -9997 values are error codes for the zero values. The line in your document with -9997 is from a source row that has l1 species values but l1cc is 0. So the zero gets caught with a validation rule.
All the other rows are cases the same as Q1 where there is no l1 species info so the row gets dropped. l2 in the source data then gets translated as CASFRI LAYER 1. This is why the crown_closure_upper_t1 and crown_closure_lower_t1 values all correspond to testvar11.

**Comment by sgautam2076** [comment]
Thank you Marc for the explanation. It makes sense to me to drop the layer if missing values and reporting layer with values as layer 1. I was confused as that polygon have both values (l1cc is 4 and l2cc is 2) in a raw but only translated layer 2. 
I think we have to capture this process in our documentation (if not yet) to tell users about dropping layer 1 if no records available for species and layer 2 is considered to be thee source information for layer 1. 
Thank you!

**Comment by edwardsmarc** [comment]
Thanks @sgautam2076 - I'll be working on the documentation in the coming weeks so I'll make sure this is properly explained.
