### ISSUE TITLE
Many QC polygons have a second layer with no information

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#554]
Layer is translated because cl_age and lookup table says num_of_layers is 2.

But layer 2 LYR is all error codes.

Only in QC03 and QC04

**Comment by MelinaHoule** [comment]
In QC03 and QC04, the number of layer is identified in the source inventory, but when layer =2, the inventory don't store any information except origin_upper and origin_lower. We would need to adjust LYR ROW_translation to only translate LYR from layer 1 if we want to drop layer 2 (since we know nothing about it) or to fix  validation rules of origin_lower and origin_upper to allow those to attributes to be translated.

**Comment by edwardsmarc** [comment]
Technically I think I we should return all UNKNOWN_VALUE here. We know there is a layer but we don't know what's in it.

This would require solving #556

**Comment by edwardsmarc** [comment]
We have already solved this issue. Looking at the translation table all attributes return -8886 (unknown_value) when layer is 2. closing
