### ISSUE TITLE
ON01 - How to interpret STKG (stocking) attribute

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#603]
The **stkg** and **ustkg** attributes are the most likely candidates to translate into CROWN_CLOSURE_UPPER/LOWER (LYR & NFL). From the manual: "The stocking attribute indicates a qualitative measure of the density of tree cover in a forest stand. It is expressed as a percentage value ranging from zero, for recently disturbed stands, to a maximum of 4.00, although 2.50 is the typical maximum value encountered in the field. Stocking of a forest stand refers to all species that make up the stand's canopy, but it is generally based on the species with the most basal area."

For us, the problem is twofold: are these 2 attributes appropriate to translate into crown closure? and, if so, how do we translate the values into percentages? There are no clear rules in the manual or the specifications.

Any thoughts? @MelinaHoule do you know how this was dealt with in CAS04, if at all? If not, do we contact John Cosco or the original data provider?

**Comment by prvernier** [comment]
Note that after we resolve the above issue, we will need a helper functions that applies 1) the function in the LYR translation table for ON02 and 2) a new (as of yet unwritten) function for ON01. The latter would be based on the translation rules for values 0-4.00 that we eventually come up with.

**Comment by edwardsmarc** [comment]
Email from JC:

_Attached is the part of my document concerning stocking. Stocking is an odd value used in Ontario FRI based on basal area. Called the stocking factor, it is the ratio of the actual basal area per ha (photo interpreted based on field samples) compared to what was considered an optimal or normal basal area using tables developed by Plonski. Basal area is difficult to estimate at the best of times so photo interpretation used crown closure to estimate stocking. The stocking value was used to determine volume and yield estimates. I attach a scan of two covers of Plonski documents. It is important to note that it is polygon specific and not layer-specific (which would have been more representative of where the basal area is most concentrated)._

_The stocking value, instead of crown closure, was used for FRI up to 2007. Crown closure was not recorded in those early inventories except as an enhancement in a few inventories. In 2007 crown closure replaced the stocking value. This did not work out too well for determining volumes and yields so around 2010 stocking value was returned to the classification._

_The reason crown closure is not a good substitute for stocking (besides being apples and oranges) is that there is a whole range of cover types in Ontario and one size does not fit all. It would be difficult to produce crown closure to stocking tables for each species group. Crown closure usually works reasonably well with crown closure percents 30 to 60% then on either end of this range, it starts to be more problematic (large swings in stocking values for similar-looking stands). Part of the problem was that Ontario did not like to see values greater than 1.0 which added quite a bias to the process. My table would be a good starting place for conversion._


**Based on this, it seems like translating stocking to CC could be a stretch for CASFRI. We don't translate any other basal area measures to crown closure. Any translation would have high uncertainty.**

**Comment by prvernier** [comment]
I agree, this approach doesn't seem compatible with how CC is estimated in other districts.
