### ISSUE TITLE
YT03 - Disturbance attributes

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/CASFRI#648]
YT03 includes 4 sets of disturbance attributes that describe type, year, extent and layer. The latter attribute identifies whether the disturbance affects the entire polygon or is in layer 1 or 2. For example, values for disturbance1_layer look like this:
<pre>
------------------------------------------------------------------------------------------
No   Variable   Stats / Values                  Freqs (% of Valid)   Valid      Missing   
---- ---------- ------------------------------- -------------------- ---------- ----------
1    x          1. Entire polygon disturbed      1409 ( 6.5%)        21727      49346     
     [factor]   2. Layer 1 disturbance          20306 (93.5%)        (30.57%)   (69.43%)  
                3. Layer 2 disturbance             12 ( 0.1%)                             
------------------------------------------------------------------------------------------
</pre>

The attribute disturbance2_layer also contains the same 3 values (the other 2 only have one value each and are not a concern).

A helper function is therefore needed for the first 2 disturbance types to correctly allocate them to layer 1 or layer 2.

**Comment by edwardsmarc** [comment]
What layer(s) should disturbances be assigned to when they are labelled "Entire polygon disturbed"??
  - Layer 1 only?
  - Both layers 1 and 2?

I would say they should be reported for both layer 1 and 2. In which case we will need to run the DST translation twice, so there will be 2 rows in attribute_dependencies.

**ROW_TRANSLATION_RULE**
- Select all rows with a disturbance 1, disturbance 2, disturbance 3 or disturbance 4 value.

**Layer 1**
- Custom function will make a list of disturbance values that are labelled either "Entire polygon disturbed" or "Layer 1 disturbance". The first in the list will be returned as dst 1, then dst 2 etc.

**Layer 2**
- Custom function will make a list of disturbance values that are labelled either "Entire polygon disturbed" or "Layer 2 disturbance". The first in the list will be returned as dst 1, then dst 2 etc.

Make the custom function so that it takes a string list of source layer values, and a second string list of the src values to translate (e.g. disturbance types). Filter the second string list using the first string list (based on the layer logic described above), grab the correct index (i.e. 1 for dst_type_1 etc.), then pass the values to translation rules. This could probably be a custom matchList function that could be used for both dst_type and dst_extent.

Custom validation function would need to check the number of disturbances and return NOT_APPLICABLE where appropriate.

Note that for disturbances reported in both layers, they wouldn't always be assigned the same layer number. For example a fire that effected the entre polygon could be dst_type_1 in layer 2 but dst_type_2 in layer 1. I don't think this matters.
