### ISSUE TITLE
Define some rules to distinguish updates from new inventories. 

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/CASFRI#68]
* When is an updated FRI considered a new inventory vs. an update.
* For example in BC, should newly available downloads be added as new FRIs or updates to the existing FRI.

**Comment by pedrogit** [comment]
Good question. Maybe we could follow our own rule about data versionning (see CAFRI readme) to determine if a new inventory is worth a new version number.

**Comment by MelinaHoule** [comment]
I propose, for open source data, there is always a "Date of publication" associated with the data product. We should make sure that date is at least one year appart. For inventories received by a collaborator, we make sure the date of acquisition is at least one year appart if the inventory data follow the same standard. For example, we got 2 version of QC 4inv because it took 9 years for them to finish it. We thus have a Qc 4inv that is half 3rd, half 4th and then we have the full 4th inventory.  If it's a new inventory, no question asked, we take it. 

What do you think? 

@prvernier  does BC09 and BC10 have a date of publication that is at least 1 year appart?

**Comment by pedrogit** [comment]
Why such a difference between "open source" (what does that mean? Available online?) inventories and the ones received by a collaborator (what does that mean?)?

Yes year of publication or date of acquisition could be a criteria to differenciate true updates from false updates but what if two inventories separated from one year are identical or what if a real update is published within one year from the acquisition (or the publication) of the preceding one? There must be other criterias.

**Comment by prvernier** [comment]
BC09 and BC10 are from the same vintage (2018), just structured differently.

**Comment by MelinaHoule** [comment]
Available online means you download it yourself. The date of download doesn't mean anything. What matters is the year the inventory was publish online. I don't see why a provinces would publish the exact same inventory but would change the date of publication... If the date of publication change, it means there were some updates. It can be disturbance, depletion, .... but something would differ. 

If the inventory comes from a collaborator, that involve a discussion. So it is easy to make sure we are not incorporating something that we already have.  I

If a real update is plublish within 1 year, we wait the year after. I mean, we don't plan of having a real-time forest inventory DB.

**Comment by MelinaHoule** [comment]
Close with commit a1a410172f99579d8b8f2c4c40183e95d84480a4

**Comment by MelinaHoule** [comment]
@edwardsmarc  can you review my text. Thanks @pedrogit  check the level of precision
