### ISSUE TITLE
CASFRI translations while stands have two age classes (QC)

### ISSUE THREAD

**Issue by sgautam2076** [edwardsmarc/CASFRI#694]
Hello All;
CASFRI translation seems fine for plots with single age class but reported as -8886 if plots have two age classes (which is the case for Quebec). I think its better not to loose information for plots with two age classes. Simply, we may implement same CASFRI translation rule as used for a stand with single age stands for a few translated attributes (e.g., crown closure). 

However, the origin_lower and origin_upper should be treated differently. In that case, I think we can have following rules.
Origin_lower =  Photo year – higher age class
Origin_upper = Photo year – higher age class

For example, if the photo year is 2001 and age 12070 the CASFRI reported as 181 for both Origin_lower and Origin_lower. In this case, I am thinking it would be nice to have Origin_lower =  1881 and Origin_upper = 1931.

**Comment by MelinaHoule** [comment]
Instead of passing the age column (fifth parameter), we would need to pass the layer being processed to  qc_origin_translation(). If Layer =1, than the function will extract the age from l1_age_origin and calculate origin. If Layer = 2, age in l2_age_origin will be passed to the function. 

@edwardsmarc  would it be possible to apply that solution?

**Comment by edwardsmarc** [comment]
I don't fully understand the goal here.

Is it as @sgautam2076 suggests to have different ORIGIN_UPPER and ORIGIN_LOWER values for the same row, that indicate the full range of values for both layers?

Or is it as @MelinaHoule suggests that CASFRI layer 1 and layer 2 rows would have different origin values but ORIGIN_UPPER and ORIGIN_LOWER would still be the same within each layer?

I think @MelinaHoule's solution matches the CASFRI specs better.

If that is the goal, solution is to change
```qc_origin_translation(lookupInt(cl_age, 'translation', 'qc_standstructure_lookup', 'source_val', 'l1_age_origin', TRUE), stand_photo_year)```
to
```qc_origin_translation(lookupInt(cl_age, 'translation', 'qc_standstructure_lookup', 'source_val', origin_layer, TRUE), stand_photo_year)```
and set origin_layer to match layer in attribute_dependencies.

**Comment by MelinaHoule** [comment]
If we were dropping the creation of layer 2, it would make sense to create a range of year of origin. But  layer 2 is created  when there is double age class. So I think it would make more sense to report the second age class in layer 2 .

**Comment by sgautam2076** [comment]
If layer 1 and layer to is based on the age classes, then I think it makes sense two use age differently. However, I am not quite clear if there is additional information (e.g., height, crown closure) layer 2.  If there is no additional information for layer 2, may be dropping layer 2 and providing range for origin would make more sense.

**Comment by MelinaHoule** [comment]
There is no additionnal information other than origin_upper and origin_lower for layer 2 in QC02, QC03, QC04, QC06. That topic was discussed in #554 . Does it matter  if we indicate a polygon as MULTI_LAYERED, but only one layer is translated? Is there a constraint that expect layer 2 to exist for MULTI_LAYERED features?

**Comment by sgautam2076** [comment]
Yes, it looks complicated. As I am unable to follow corresponding documents (as they are in French), I could not understand well. What ever I understood the data, I feel like that dropping layer 2 would make more sense. I think, if two age classes may be considered as mixed structure or complex structure of a single layer stand (my guess).

My apology for not following the earlier discussion https://github.com/edwardsmarc/CASFRI/issues/554.

**Comment by MelinaHoule** [comment]
The reason why we did not drop layer 2 is because height and crown closure are associated to layer 1. I translated the definition the best I can: 

Age class: Age class indicates both the structure of the stand and the age of its each layer. A stand can be considered multi layered only if the two layers have height at least 5 m apart. Age class is thus dictated by the stem height structure of the stand. The order is assigned according to their dominance, i.e. layer which occupies the highest percentage of basal area goes first. 

Height class: In stands with multi-layered structure, the stand height will be that of the layer which occupies the highest percentage of basal area.

Crown closure: Determined by the projection alone of the percentage of crown cover. Stems considered for the evaluation of the crown closure is established according to those considered in stand height attribute, i.e. the layer which occupies the highest percentage of basal area.

But all species are translated in layer 1 and I realize that may not be the case. Somewhere in the manual it is written: The photo-interpreter must specify the species composition for stands 7 m and more in height. That means species are stated no matter the layer (or age class) to which they belong. 

I guess what @sgautam2076 proposed would make more sens. We drop layer 2, we report a range of origin. What do we do with height and crown closure? We fill the upper limit and mark the lower limit as UNKNOWN_VALUE?

**Comment by sgautam2076** [comment]
Regarding height and crown closure, I think implementing the similar translations as done for a plot with the single age class would be good. 
For example, if the crown closure code is A and age 30120, still we can have crown_colosure_lower is 80 and Crown_closure_upper is 100. Because we can not separate stand with age 30 and 120 and have their crown closure values.
Same would be valid for height as well.

**Comment by MelinaHoule** [comment]
The example above works when crown_closure upper limit is 80-100%. But if age class 9070 with crown closure 40-60%, height 17m-22m. 

We know crown closure is for the stem  having 17-22m. We don't know the crown closure for the entire polygon, but we know the lower limit is at least  40%, and probably higher than 60% when we combine the 2 strata. If we write an upper limit of  60%, we state something we don't know. 

Same thing for height. Knowing that the 2 layers are at least 5m apart (according to the definition) and the height of the dominant layer is 12-17m, we can set the upper limit, but not the lower without falling into interpretation. The second strata could have a height less than 7m.

**Comment by sgautam2076** [comment]
In your given scenario, I was thinking the CASFRI translation simply would be the following.
Crown closure lower is 40% and crown closure upper is 60%
Height lower is 17m and height lower is 22m


My perception is that crown closure and height are aggregated for that polygon, which has two age classes. 
You are right, the lower limit for crown closure is at least 40%. However, I am not clear why the upper limit can not be reported 60%. Do you mean the crown closure is measured for the first one (i.e., 90 year strata)? If this is true then we can not report upper limit.
However, if the crown closure is for a polygon representing combined age classes (i.e., 9070) then I do not see problem to report crown closure upper as 60%.

**Comment by MelinaHoule** [comment]
Height and crown closure are not given at the polygon level in the old QC inventories. They represent the value of the dominant strata. When single age class is used, it's not a problem. But with double age class, height and crown closure are associated with the dominant strata only.  The second strata has height and crown closure unknown. Species composition is however given all the time at the polygon level.

@edwardsmarc, what do you think about we change the rules. We drop the translation of layer 2, report origin according to a range of age, set height upper bound using the source value, lower bound as unknown, crown closure lower bound using the source value and upper bound as unknown unless crown closure reach 100% for the first strata? Do we keep stand_structure MULTI_LAYERED even if we combine both layer into a single one?

**Comment by edwardsmarc** [comment]
Just to make sure I am following correctly, is this the information we have for each layer in the source data:

Layer 1
Species: we have species but we don't which layer they belong to
Height: known
Crown closure: known
Origin: known

Layer 2
Species: we have species but we don't which layer they belong to
Height: unknown
Crown closure: unknown
Origin: known

This is a strange case in that species values are reported at the polygon level, so we know there are two layers, but we don't which species are assigned to which layer. For that reason the data don't really fit into the CASFRI specifications. We'll just have to choose the most logical translation and document the compromise in the translation table description and in the readMe _Translation exceptions_ section.

The only problem I see with @MelinaHoule's solution is that NUM_OF_LAYERS will now be 1, but we know the STAND_STRUCTURE is MULTI_LAYERED. This violates the constraints.

Another problem is that we will be representing 2 source layers in a single layer of CASFRI data. This goes against what we do elsewhere, but maybe that is the best compromise in this case.

Solutions:
1. Apply Melina's solution, document the fact that this standard violates the specifications.
2. Apply Melina's solution, change STAND_STRUCTURE from MULTI_LAYERED to SINGLE_LAYERED. I don't like this.
3. Apply Melina's solution, but still translate a second layer with all attributes as UNKNOWN_VALUE. This will keep NUM_OF_LAYERS at 2 so the specs will be satisfied. I don't like this solution because it's misleading to the user. We would have 2 CASFRI layers, but all the information for source layers 1 and 2 would be summarised in CASFRI layer 1.
4. We keep the existing translation, but report origin separately for layer 1 and layer 2, and we document that species are at the polygon level.

I think options 1 or 4 are our best choices. I prefer option 4 (assuming my above interpretation of the data is correct) because it fits the specs best. The only violation is that species are not accurately assigned to layers.

**Comment by sgautam2076** [comment]
Thank you, Marc for summarizing the information. 
Yes, I agree with you that this is the strange case and don't really fit into CASFRI specifications. Having most logical translation and documenting the compromises is the way to move forward. It is clear we can not fix the issues at the moment.

@edwardsmarc  Your options either 1 or 4 is the one we could choose. While choosing options 4 we would still miss height and crown closure for layer 1 if a polygon has two age classes. So, I am for options 1 and document where the translation differs from CASFRI specifications.

**Comment by edwardsmarc** [comment]
@sgautam2076 what do you mean by "While choosing options 4 we would still miss height and crown closure for layer 1 if a polygon has two age classes."?

In the case of a polygon with 2 age classes (i.e. 2 layers), we currently translate the height and crown closure for layer 1, and report height and crown closure for layer 2 as UNKNOWN. This matches what @MelinaHoule describes above from the manual.

**Comment by sgautam2076** [comment]
@edwardsmarc You mentioned that in options 4 we keep exiting translation. I understood "keep exiting translation" is meaning to use the translation that we have currently. If so, the crown closure and height only translated for polygon with one age class. If two classes it would report -8886.

Your second section "In the case of a polygon with 2 age classes (i.e. 2 layers), we currently translate the height and crown closure for layer 1, and report height and crown closure for layer 2 as UNKNOWN."  is good and clear.

**Comment by sgautam2076** [comment]
![CrownClosure](https://user-images.githubusercontent.com/65095356/113036761-a8d0a280-9162-11eb-8f7a-2da39744b372.PNG)

**Comment by sgautam2076** [comment]
Thank you @edwardsmarc and @MelinaHoule for your efforts. Yes, the solution looks good to me and looking forward to new release.
Yes, height translation seems fine (except an issue for Q4 data - see screen shot below . If height value is 1 in inventory data, it was reported to -9999 in CASFRI translation. I guess something is happening there, but I could not figure out why. 

![Height_qc04](https://user-images.githubusercontent.com/65095356/113059116-0ffb5080-917d-11eb-863e-04b584e6a7a1.PNG)
)

**Comment by edwardsmarc** [comment]
Those error codes for height values of 1 should be fixed in tomorrows release. Although I'm not able to find what could have caused them in older versions of the table. Are you able to send me the HEIGHT validation functions that were used to create your example?

**Comment by sgautam2076** [comment]
Thank you, Marc.
Please find the SQL code that I have used. I hope my code makes sense.

DROP table test_casfri50.test_rawfri_cas_l2_qc04;
CREATE TABLE test_casfri50.test_rawfri_cas_l2_qc04 AS
SELECT 
REPLACE(substring(n.geocode, 1, 10), ',', '.') AS coord1,
REPLACE(substring(n.geocode, 11, 10), ',', '.') AS coord2,
	c.cas_id, 
	c.height_lower,
	c.height_upper,
	c.layer, 
	n.cl_haut
FROM rawfri.qc04 n
JOIN 
(
	select *, 
	ltrim(split_part(cas_id, '-', 2), 'x') AS src_filename,
	REPLACE(RTRIM(substring(cas_id, 22, 10), '+'), 'x', '') map_id,
	REPLACE(RTRIM(substring(cas_id, 33, 10), '+'), 'x', '') poly_id,
	--ltrim(split_part(cas_id, '-', 3), '+') AS map_id,	
	--ltrim(split_part(cas_id, '-', 4), '+') AS poly_id, 
	ltrim(split_part(cas_id, '-', 5), 'x') AS ogc_fid
FROM lyr_all WHERE cas_id ILIKE 'qc04%' and layer =1
) c
ON REPLACE(substring(n.geocode, 1, 10), ',', '.') = c.map_id::text AND REPLACE(substring(n.geocode, 11, 10), ',', '.') = c.poly_id::text;


---- height
SELECT DISTINCT left(cas_id, 4) inv, string_agg(layer::text, ', ' ORDER BY layer) layers, 
                string_agg(cl_haut::text, ', ') height, string_agg(height_lower::text, ', ') height_lower,
				string_agg(height_upper::text, ', ') height_upper 
FROM test_casfri50.test_rawfri_cas_l1_qc04 
GROUP BY cas_id ORDER BY height ASC;

**Comment by edwardsmarc** [comment]
closed with 5331ea8e2b169d1bad6b80bb06bcde293c60f670
